# ----------------------------------------------------------------------------------------------------------------------------------------------------------------
MAPPING_PARAM = {'일일'           : 'daily',
                 'daily'          : 'daily',
                 '점검'           : 'check',
                 '일일점검'       : 'daily_check',
                 'check'          : 'check',
                 '실시간'         : 'realtime',
                 '현재'           : 'current',
                 '범위'           : 'range',
                 '월간'           : 'monthly',
                 'monthly'        : 'monthly',
                 '상세'           : 'detail',
                 'detail'         : 'detail',
                 '리소스'         : 'resource',
                 'resource'       : 'resource',
                 '사용량'         : 'resource',
                 'usage'          : 'resource',
                 '오라클'         : 'oracle',
                 'oracle'         : 'oracle',
                 '시퀄'           : 'mssql',
                 '씨퀄'           : 'mssql',
                 'ms-sql'         : 'mssql',
                 'mssql'          : 'mssql',
                 'mysql'          : 'rds',
                 '기타'           : 'etc',
                 'etc'            : 'etc',
                 '에러'           : 'err',
                 'error'          : 'err',
                 'err'            : 'err',
                 '배치'           : 'batch',
                 'batch'          : 'batch',
                 '넷백업'         : 'netbackup',
                 'netbackup'      : 'netbackup',
                 # resource keywords
                 'cpu'            : 'cpu',
                 '씨피유'         : 'cpu',
                 '시피유'         : 'cpu',
                 '메모리'         : 'memory',
                 'mem'            : 'memory',
                 'memory'         : 'memory',
                 '파일시스템'     : 'storage',
                 'filesystem'     : 'storage',
                 '디스크'         : 'storage',
                 'disk'           : 'storage',
                 '스토리지'       : 'storage',
                 'storage'        : 'storage',
                 '테이블스페이스' : 'storage',
                 'tablespace'     : 'storage',
                 'request'        : 'request',
                 '요청'           : 'request',
                 'transaction'    : 'transaction',
                 '트랜잭션'       : 'transaction',
                 'bufferhit'      : 'bufferhit',
                 'buffer'         : 'bufferhit',
                 'hit'            : 'bufferhit',
                 '히트'           : 'bufferhit',
                 '버퍼'           : 'bufferhit',
                 'exec'           : 'exec',
                 'execution'      : 'execution',
                 '실행'           : 'execution',
                 'sess'           : 'session',
                 'session'        : 'session',
                 '세션'           : 'session',
                 # etc keywords
                 'dr'             : 'dr',
                 'bcv'            : 'bcv',
                 # 서버명과 중복이라서 제거
                 # '동기화'         : 'sync',
                 'sync'           : 'sync',
                 # for multi selectable variables
                 '전체'           : 'All',
                 # serverName keywords
                 # issue : this mapping is attatched to url
                 #         need to find a way not to so
                 # ANS : by "remap_request" it is not supposed to be here. seperate to serverHosts
                # 'AND#1'          : '[POS] AND#1',
                # ... 생략 ...
                # 'DRM'            : '[인프라] DRM',
                 # work keywords
                 '근태'           : 'work',
                 '파트'           : 'part',
                 '개인'           : 'indivisual',
                # for help
                 'help'           : 'help',
                 '도움말'         : 'help',
                 '헬프'           : 'help',
                 '도움'           : 'help',
                 '사용법'         : 'help',
                # for keywork
                 'keyword'        : 'keyword',
                 '키워드'         : 'keyword'
                }



SERVERHOSTS = {'and#1'          : '[POS] AND%231',
               'and#2'          : '[POS] AND%232',
               'ams'            : '[POS] AMS',
               '푸드#1'         : '[POS] 푸드키오스크%231',
               '푸드#2'         : '[POS] 푸드키오스크%232',
               '키오스크#1'     : '[POS] 푸드키오스크%231',
               '키오스크#2'     : '[POS] 푸드키오스크%232',
               '푸드키오스크#1' : '[POS] 푸드키오스크%231',
               '푸드키오스크#2' : '[POS] 푸드키오스크%232',
               '동기화'         : '[POS] 동기화',
               '매출'           : '[POS] 매출',
               'scom'           : '[POS] SCOM',
               'sccm'           : '[인프라] SCCM',
               '아카이브'       : '[MD] 아카이브',
               '상품권'         : '[상품권] 상품권',
               '문화센터'       : '[마케팅] (신)문화센터',
               '사은'           : '[마케팅] (신)사은',
               '에누리'         : '[마케팅] (신)에누리',
               'drm'            : '[인프라] DRM',
               '영업통합#1'     : 'LPSIS1',
               '영업통합#2'     : 'LPSIS2',
               '인사#1'         : 'LOTTEHRS1',
               '인사#2'         : 'LOTTEHRS2',
               '(구)전자저널'   : '[POS] (구)전자저널',
               'sap'            : '[재무] SAP',
               '동료사원'       : '[경영지원] 동료사원',
               '메신저'         : '[경영지원] 메신저',
               '전자결재'       : '[경영지원] 전자결재',
               'im'             : '[경영지원] IM',
               '계정관리'       : '[경영지원] IM',
               '법인영업'       : '[마케팅] 법인영업',
               '내부회계'       : '[재무] 내부회계',
               '재무통합'       : '[재무] 재무통합',
               '증빙'           : '[재무] 증빙',
               '통합구매'       : '[재무] 통합구매',
               'eai'            : '[재무] EAI',
              }