{
 "title": "daily check SE",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PartNm", "query": "재무, MD" }
  ]
 },
 "panels": [
  {
   "title": "daily check server resource",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT [파트명]\n     , [호스트]\n     , [서비스명]\n     , [CPU 사용량(%)]\n     , [메모리 사용량(%)]\n     , [디스크 95%초과수]\n     , [등록일시]\n  FROM (SELECT A.PART_CL_CD [파트명]\n             , A.hostName AS [호스트]\n             , A.serviceName AS [서비스명]\n            -- , A.IP_ADDR AS [IP]\n             , B.CPUUSE AS [CPU 사용량(%)]\n             , B.MEMUSE AS [메모리 사용량(%)]\n             , B.DSKCHK AS [디스크 95%초과수]\n             , B.RGST_DTM [등록일시]\n             , ROW_NUMBER() OVER (PARTITION BY a.hostname order by b.rgst_dtm desc) rnk\n          FROM TB_SVR_COMM_INFO_M (NOLOCK) A\n          LEFT OUTER JOIN TB_SVR_RSRC_CHK_L  (NOLOCK) B\n            ON A.hostName = B.hostName\n           AND B.COLLECTDT = CONVERT(VARCHAR, GETDATE(), 112) \n         WHERE A.RSRC_YN = 'Y'\n           AND A.PART_CL_CD IN ($PartNm)\n        ) Z\n  WHERE rnk = 1\nORDER BY [파트명], [서비스명]\n",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "daily check server status",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT z.PART_CL_CD [파트명], z.hostName [호스트명], z.serviceName [서비스명]\r\n     , MAX([CPU 상태]          ) AS [CPU 상태]\r\n     , MAX([Memory 상태]       ) AS [Memory 상태]\r\n     , MAX([Disk 상태]         ) AS [Disk 상태]\r\n     , MAX([Cache Battery 상태]) AS [Cache Battery 상태]\r\n     , MAX([Controller 상태]   ) AS [Controller 상태]\r\n     , MAX([Fan 상태]          ) AS [Fan 상태]\r\n     , MAX([Power Supply 상태] ) AS [Power Supply 상태]\r\n     , MAX([EventLog]          ) AS [EventLog]\r\n     , MIN(RGST_DTM) [등록일시]\r\n  FROM (\r\n        SELECT B.collectDT, A.PART_CL_CD, a.hostName, a.serviceName, b.RGST_DTM\r\n             , CASE WHEN B.statusName = 'CPU Status'        THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [CPU 상태]\r\n             , CASE WHEN B.statusName = 'Memory Status'     THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [Memory 상태]\r\n             , CASE WHEN B.statusName = 'Disk Status'       THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [Disk 상태]\r\n             , CASE WHEN B.statusName = 'Cache Status'      THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [Cache Battery 상태]\r\n             , CASE WHEN B.statusName = 'Controller Status' THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [Controller 상태]\r\n             , CASE WHEN B.statusName = 'Fan Status'        THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [Fan 상태]\r\n             , CASE WHEN B.statusName = 'PS Status'         THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [Power Supply 상태]\r\n             , CASE WHEN B.statusName = 'Event Log'         THEN CASE STATUS WHEN 'OK' THEN 0 WHEN 'NOK' THEN 1 ELSE 2 END END AS [EventLog]\r\n             , ROW_NUMBER() OVER (PARTITION BY a.hostname, b.statusName order by b.rgst_dtm desc) rnk\r\n          FROM TB_SVR_COMM_INFO_M (NOLOCK) A\r\n          LEFT OUTER JOIN [TB_Svr_Stat_Chk_L]  (NOLOCK) B\r\n            ON A.hostName = B.hostName\r\n           AND B.collectDT = CONVERT(VARCHAR, GETDATE(), 112) \r\n         WHERE 1=1\r\n           AND A.STAT_YN = 'Y'\r\n           AND A.PART_CL_CD IN ($PartNm)\r\n  ) z\r\n  WHERE RNK = 1\r\nGROUP BY z.PART_CL_CD, z.hostName, z.serviceName",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "netbackup check",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT JobID, Client, Schedule, Policy, format(Started,'yyyy-MM-dd HH:mm:ss') Started, format(Ended,'yyyy-MM-dd HH:mm:ss') Ended\r\n     , case  State when 'Done' then 0 when 'Active' then 1 else 2 end as State , Elapsed, Active_Elapsed, Status\r\n     , Dest_Media_Svr, Dest_StUnit, Attempt, Completion, Owner\r\n  FROM [TB_Bak_Stat_Chk_L]\r\n WHERE 1=1\r\n   AND collectDT = convert(varchar(8),getdate(),112)",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}