{
 "title": "work check",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "PartNm",
    "query": "SELECT TITLE AS PART_NM \n  FROM  DPT (nolock) D \nWHERE TITLE <> '관리자'\nORDER BY CASE WHEN TITLE = 'MD'       THEN 1\n              WHEN TITLE = '마케팅'   THEN 2\n              WHEN TITLE = '경영지원' THEN 3\n              WHEN TITLE = '재무'     THEN 4\n              WHEN TITLE = 'POS'      THEN 5\n              WHEN TITLE = '상품권'   THEN 6\n              WHEN TITLE = '인프라'   THEN 7\n              ELSE 99 -- 매니저\n          END "
   },
   {
    "name": "MemNm",
    "query": "SELECT M.MEMBERNM\n  FROM MEMBER (NOLOCK) M\n INNER JOIN DPT (NOLOCK) D\n    ON M.DPTNO = D.ID\n WHERE M.USEYN = 1\n    AND D.TITLE in($PartNm)\n ORDER BY CASE WHEN D.TITLE = 'MD'       THEN 1\n               WHEN D.TITLE = '마케팅'   THEN 2\n               WHEN D.TITLE = '경영지원' THEN 3\n               WHEN D.TITLE = '재무'     THEN 4\n               WHEN D.TITLE = 'POS'      THEN 5\n               WHEN D.TITLE = '상품권'   THEN 6\n               WHEN D.TITLE = '인프라'   THEN 7\n               ELSE 99 -- 매니저\n           END "
   },
   { "name": "IndivisualNm" }
  ]
 },
 "panels": [
  { "title": "Working Sheet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "월_파트비용",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT substring(convert(varchar,getdate(),121),1,7) [기준월], MAX(c.TITLE) OVER(PARTITION BY B.DPTNO) [부서], FORMAT(sum(a.PRICE) OVER(PARTITION BY B.DPTNO), N'#,0') [총사용금액] \r\n, FORMAT(A.PRICE, N'#,0') [금액], A.MEMBERNM [사용자], A.CONTENT [목적], A.SHOPNAME [장소], CONVERT(VARCHAR,A.USEDATE,23) [사용일자]\r\n, CASE WHEN A.CONTENT LIKE '%간담회%' AND A.CONTENT NOT LIKE '%생일%' THEN '간담회'\r\n       WHEN A.CONTENT LIKE '%회식%' AND A.CONTENT NOT LIKE '%생일%' THEN '회식' \r\n       WHEN A.CONTENT LIKE '%책임당직%' THEN '책임당직' \r\n       ELSE 'NA' END AS [구분자]\r\n  FROM (SELECT Z.USEDATE, Z.MEMBERID, Z.PRICE, RANK() OVER (PARTITION BY Z.GROUPID ORDER BY Z.TARGETMBRID DESC) RNK \r\n             -- \r\n             , Z.MEMBERNM, Z.CONTENT, SHOPNAME\r\n        FROM OVERTIMEPRICE Z with (nolock)\r\n        -- 이번달\r\n        WHERE 1=1\r\n        AND  Z.USEDATE  BETWEEN CONVERT(DATETIME,DATEADD(D,-DAY(CAST(CAST(GETDATE() AS DATE) AS DATETIME))+1,CAST(CAST(GETDATE() AS DATE) AS DATETIME))) AND GETDATE()\r\n     --    and z.usedate >= '2023-05-01'     \r\n        )  a, MEMBER b, DPT c\r\n WHERE 1=1\r\n   AND RNK = 1\r\n   AND A.MEMBERID = B.ID\r\n   AND B.DPTNO = C.ID \r\n   AND C.TITLE IN ($PartNm)\r\n"
    }
   ]
  },
  {
   "title": "work",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT /*GETDATE() AS WORK_DT, */PIVOT_RESULT.* \r\n  FROM (SELECT D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             --, ISNULL(W.TITLE,'정상출근') AS WORK_TYPE--, S.CONTENT, S.CONTENT2\r\n             --, CASE WHEN W.TITLE IS NULL                             THEN '정상근무' \r\n             --       WHEN W.TITLE = '점검'                            THEN '정상근무'\r\n             --       WHEN W.TITLE = '근무' AND S.CONTENT = '재택근무' THEN '재택근무'\r\n             --       WHEN W.TITLE = '교육 및 세미나'                  THEN '교육'\r\n             --       WHEN W.TITLE IN ('외근','출장')                  THEN '외근'\r\n             --       WHEN W.TITLE IN ('휴가','휴무(연차/대휴)')       THEN '휴가'\r\n             --       ELSE '기타일정'\r\n             --   END AS WORK_TYPE\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '정상근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                    ELSE '기타일정'\r\n                END AS WORK_TYPE\r\n          FROM MEMBER (NOLOCK) M\r\n    INNER JOIN DPT (NOLOCK) D\r\n            ON M.DPTNO = D.ID\r\n           AND D.TITLE IN ($PartNm)\r\n    LEFT OUTER JOIN SCHEDULE (NOLOCK) S\r\n            ON M.ID = S.MEMBERID\r\n           AND GETDATE() BETWEEN S.STARTDATE AND S.ENDDATE\r\n    LEFT OUTER JOIN DUTY (NOLOCK) W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n       ) AS RESULT\r\n--PIVOT(COUNT(MEM_NM) FOR PART_NM IN(['교육 및 세미나'],['근무'],['기타일정'],['외근'],['점검'],['정상출근'],['출장'],['휴가'],['휴무(연차/대휴)'])) AS PIVOT_RESULT\r\nPIVOT(COUNT(MEM_NM) FOR WORK_TYPE IN([정상근무],[재택근무],[교육],[외근],[휴가],[기타일정])) AS PIVOT_RESULT\r\n-- PART CODE는 따로 SELECT 하지 않음\r\nORDER BY CASE WHEN PART_NM = 'MD'       THEN 1\r\n              WHEN PART_NM = '마케팅'   THEN 2\r\n              WHEN PART_NM = '경영지원' THEN 3\r\n              WHEN PART_NM = '재무'     THEN 4\r\n              WHEN PART_NM = 'POS'      THEN 5\r\n              WHEN PART_NM = '상품권'   THEN 6\r\n              WHEN PART_NM = '인프라'   THEN 7\r\n              ELSE 99 -- 매니저\r\n          END "
    }
   ]
  },
  {
   "title": "work part",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "        SELECT D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             --, ISNULL(W.TITLE,'정상출근') AS WORK_TYPE\r\n             --, CASE WHEN W.TITLE IS NULL                             THEN '정상근무' \r\n             --       WHEN W.TITLE = '점검'                            THEN '정상근무'\r\n             --       WHEN W.TITLE = '근무' AND S.CONTENT = '재택근무' THEN '재택근무'\r\n             --       WHEN W.TITLE = '교육 및 세미나'                  THEN '교육'\r\n             --       WHEN W.TITLE IN ('외근','출장')                  THEN '외근'\r\n             --       WHEN W.TITLE IN ('휴가','휴무(연차/대휴)')       THEN '휴가'\r\n             --       ELSE '기타일정'\r\n             --   END AS WORK_TYPE\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '정상근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                --     ELSE '기타일정'\r\n                    ELSE S.CONTENT + ' ' + S.CONTENT2\r\n                END AS WORK_TYPE\r\n             , S.CONTENT + ' ' + S.CONTENT2 as Detail\r\n          FROM MEMBER (NOLOCK) M\r\n    INNER JOIN DPT (NOLOCK) D\r\n            ON M.DPTNO = D.ID\r\n    LEFT OUTER JOIN SCHEDULE (NOLOCK) S\r\n            ON M.ID = S.MEMBERID\r\n           AND GETDATE()-1 BETWEEN S.STARTDATE AND S.ENDDATE\r\n    LEFT OUTER JOIN DUTY (NOLOCK) W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n           AND D.TITLE in($PartNm)\r\n           AND M.MEMBERNM in($MemNm)\r\n ORDER BY CASE WHEN D.TITLE = 'MD'       THEN 1\r\n               WHEN D.TITLE = '마케팅'   THEN 2\r\n               WHEN D.TITLE = '경영지원' THEN 3\r\n               WHEN D.TITLE = '재무'     THEN 4\r\n               WHEN D.TITLE = 'POS'      THEN 5\r\n               WHEN D.TITLE = '상품권'   THEN 6\r\n               WHEN D.TITLE = '인프라'   THEN 7\r\n               ELSE 99 -- 매니저\r\n           END\r\n          , M.MEMBERID"
    }
   ]
  },
  {
   "title": "work Indivisual",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "with tbl_date as (\r\nSELECT\r\n        NUMBER M_NUM, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01') + NUMBER-1 as dt,\r\n        DATEPART(DW, CONVERT(DATETIME, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')) + NUMBER-1) M_PART,\r\n        DATENAME(DW, CONVERT(DATETIME, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')) + NUMBER-1) M_NAME,\r\n        DATEDIFF(WK, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'), DATEADD(D, NUMBER-1, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'))) WK,\r\n        (CASE CONVERT(VARCHAR(8), CONVERT(DATETIME, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')) + NUMBER - 1, 112)\r\n         WHEN CONVERT(VARCHAR(8), GETDATE(), 112) THEN ' (오늘)' ELSE '' END) TODAY\r\n    FROM MASTER..SPT_VALUES\r\n    WHERE TYPE='P'\r\n    AND NUMBER BETWEEN 1 AND DATEDIFF(D, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'), DATEADD(MM, 1, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')))\r\n)\r\nSELECT  \r\n    -- T1.WK,\r\n    '일' = MAX(CASE M_PART WHEN '1' THEN CONVERT(VARCHAR,M_NUM)+TODAY+CHAR(13)+CHAR(10)+IIF(WORK_TYPE='정상근무','점검',Detail) ELSE '' END),\r\n    '월' = MAX(CASE M_PART WHEN '2' THEN CONVERT(VARCHAR,M_NUM)+TODAY+CHAR(13)+CHAR(10)+ISNULL(WORK_TYPE,'정상근무')            ELSE '' END),\r\n    '화' = MAX(CASE M_PART WHEN '3' THEN CONVERT(VARCHAR,M_NUM)+TODAY+CHAR(13)+CHAR(10)+ISNULL(WORK_TYPE,'정상근무')            ELSE '' END),\r\n    '수' = MAX(CASE M_PART WHEN '4' THEN CONVERT(VARCHAR,M_NUM)+TODAY+CHAR(13)+CHAR(10)+ISNULL(WORK_TYPE,'정상근무')            ELSE '' END),\r\n    '목' = MAX(CASE M_PART WHEN '5' THEN CONVERT(VARCHAR,M_NUM)+TODAY+CHAR(13)+CHAR(10)+ISNULL(WORK_TYPE,'정상근무')            ELSE '' END),\r\n    '금' = MAX(CASE M_PART WHEN '6' THEN CONVERT(VARCHAR,M_NUM)+TODAY+CHAR(13)+CHAR(10)+ISNULL(WORK_TYPE,'정상근무')            ELSE '' END),\r\n    '토' = MAX(CASE M_PART WHEN '7' THEN CONVERT(VARCHAR,M_NUM)+TODAY+CHAR(13)+CHAR(10)+IIF(WORK_TYPE='정상근무','점검',Detail) ELSE '' END)\r\nFROM TBL_DATE T1 with (nolock)\r\nJOIN MASTER..SPT_VALUES T2 with (nolock)\r\n  ON T1.WK = T2.NUMBER\r\n  LEFT OUTER JOIN (SELECT CONVERT(VARCHAR(10),S.STARTDATE,121) AS WORK_ST_DT, CONVERT(VARCHAR(10),S.ENDDATE-1,121) AS WORK_END_DT, \r\n                          D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             --, ISNULL(W.TITLE,'정상출근') AS WORK_TYPE\r\n             --, CASE WHEN W.TITLE IS NULL                             THEN '정상근무' \r\n             --       WHEN W.TITLE = '점검'                            THEN '정상근무'\r\n             --       WHEN W.TITLE = '근무' AND S.CONTENT = '재택근무' THEN '재택근무'\r\n             --       WHEN W.TITLE = '교육 및 세미나'                  THEN '교육'\r\n             --       WHEN W.TITLE IN ('외근','출장')                  THEN '외근'\r\n             --       WHEN W.TITLE IN ('휴가','휴무(연차/대휴)')       THEN '휴가'\r\n             --       ELSE '기타일정'\r\n             --   END AS WORK_TYPE\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '정상근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                    ELSE '기타일정'\r\n                END AS WORK_TYPE\r\n             , S.CONTENT + ' ' + S.CONTENT2 as Detail\r\n          FROM MEMBER (NOLOCK) M\r\n    INNER JOIN DPT (NOLOCK) D\r\n            ON M.DPTNO = D.ID\r\n    LEFT OUTER JOIN SCHEDULE (NOLOCK) S\r\n            ON M.ID = S.MEMBERID\r\n           AND S.STARTDATE between CONVERT(DATETIME, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')) and DATEADD(MM, 1, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'))\r\n    LEFT OUTER JOIN DUTY (NOLOCK) W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n          -- AND D.TITLE in('MD','마케팅','경영지원','재무','POS','상품권','인프라','영업1담당','영업2담당','지원1담당','지원2담당')\r\n           AND M.MEMBERNM = '$IndivisualNm'\r\n --ORDER BY S.STARTDATE DESC\r\n ) AS WORK\r\n ON T1.DT BETWEEN WORK.WORK_ST_DT AND WORK.WORK_END_DT\r\nWHERE\r\n    T2.TYPE = 'P'\r\nGROUP BY T1.WK\r\nORDER BY T1.WK\r\n"
    }
   ]
  },
  {
   "title": "work Indivisual",
   "type": "marcusolsson-calendar-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "with tbl_date as (\r\nSELECT\r\n        NUMBER M_NUM, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01') + NUMBER-1 as DT,\r\n        DATEPART(DW, CONVERT(DATETIME, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')) + NUMBER-1) M_PART,\r\n        DATENAME(DW, CONVERT(DATETIME, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')) + NUMBER-1) M_NAME,\r\n        DATEDIFF(WK, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'), DATEADD(D, NUMBER-1, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'))) WK\r\n    FROM MASTER..SPT_VALUES\r\n    WHERE TYPE='P'\r\n    AND NUMBER BETWEEN 1 AND DATEDIFF(D, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'), DATEADD(MM, 1, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')))\r\n)\r\nSELECT  \r\n    -- T1.DT as time, \r\n    DISTINCT \r\n    CASE M_PART WHEN '1' THEN IIF(WORK_TYPE='정상근무','점검',Detail)                    \r\n                WHEN '2' THEN ISNULL(WORK_TYPE,'정상근무')        \r\n                WHEN '3' THEN ISNULL(WORK_TYPE,'정상근무')        \r\n                WHEN '4' THEN ISNULL(WORK_TYPE,'정상근무')        \r\n                WHEN '5' THEN ISNULL(WORK_TYPE,'정상근무')        \r\n                WHEN '6' THEN ISNULL(WORK_TYPE,'정상근무')        \r\n                WHEN '7' THEN IIF(WORK_TYPE='정상근무','점검',Detail)             \r\n                ELSE '' END as WORK_TYPE,\r\n                WORK.DETAIL AS DEATIL,\r\n                WORK.WORK_ST_DT,\r\n                WORK.WORK_END_DT\r\nFROM TBL_DATE T1\r\nJOIN MASTER..SPT_VALUES T2\r\n  ON T1.WK = T2.NUMBER\r\n  LEFT OUTER JOIN (SELECT CONVERT(VARCHAR(10),S.STARTDATE,121) AS WORK_ST_DT, CONVERT(VARCHAR(10),S.ENDDATE-1,121) AS WORK_END_DT, \r\n                          D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             --, ISNULL(W.TITLE,'정상출근') AS WORK_TYPE\r\n             --, CASE WHEN W.TITLE IS NULL                             THEN '정상근무' \r\n             --       WHEN W.TITLE = '점검'                            THEN '정상근무'\r\n             --       WHEN W.TITLE = '근무' AND S.CONTENT = '재택근무' THEN '재택근무'\r\n             --       WHEN W.TITLE = '교육 및 세미나'                  THEN '교육'\r\n             --       WHEN W.TITLE IN ('외근','출장')                  THEN '외근'\r\n             --       WHEN W.TITLE IN ('휴가','휴무(연차/대휴)')       THEN '휴가'\r\n             --       ELSE '기타일정'\r\n             --   END AS WORK_TYPE\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '정상근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                    -- ELSE '기타일정'\r\n                    ELSE S.CONTENT + ' ' + S.CONTENT2\r\n                END AS WORK_TYPE\r\n             , S.CONTENT + ' ' + S.CONTENT2 as Detail\r\n          FROM MEMBER (NOLOCK) M\r\n    INNER JOIN DPT (NOLOCK) D\r\n            ON M.DPTNO = D.ID\r\n    LEFT OUTER JOIN SCHEDULE (NOLOCK) S\r\n            ON M.ID = S.MEMBERID\r\n           AND S.STARTDATE between CONVERT(DATETIME, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01')) and DATEADD(MM, 1, CONVERT(DATETIME, SUBSTRING($__timeFrom(),1,8) + '01'))\r\n    LEFT OUTER JOIN DUTY (NOLOCK) W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n          -- AND D.TITLE in('MD','마케팅','경영지원','재무','POS','상품권','인프라','영업1담당','영업2담당','지원1담당','지원2담당')\r\n           AND M.MEMBERNM = '$IndivisualNm'\r\n           and content <> '공휴일'\r\n --ORDER BY S.STARTDATE DESC\r\n ) AS WORK\r\n ON T1.DT BETWEEN WORK.WORK_ST_DT AND WORK.WORK_END_DT\r\nWHERE\r\n    T2.TYPE = 'P'\r\n"
    }
   ]
  },
  {
   "title": "work Indivisual (TEXT)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "        SELECT CONVERT(VARCHAR(10),S.STARTDATE,121) AS STARTDATE, D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             --, ISNULL(W.TITLE,'정상출근') AS WORK_TYPE\r\n             --, CASE WHEN W.TITLE IS NULL                             THEN '정상근무' \r\n             --       WHEN W.TITLE = '점검'                            THEN '정상근무'\r\n             --       WHEN W.TITLE = '근무' AND S.CONTENT = '재택근무' THEN '재택근무'\r\n             --       WHEN W.TITLE = '교육 및 세미나'                  THEN '교육'\r\n             --       WHEN W.TITLE IN ('외근','출장')                  THEN '외근'\r\n             --       WHEN W.TITLE IN ('휴가','휴무(연차/대휴)')       THEN '휴가'\r\n             --       ELSE '기타일정'\r\n             --   END AS WORK_TYPE\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '정상근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                    ELSE '기타일정'\r\n                END AS WORK_TYPE\r\n             , S.CONTENT + ' ' + S.CONTENT2 as Detail\r\n          FROM MEMBER (NOLOCK) M\r\n    INNER JOIN DPT (NOLOCK) D\r\n            ON M.DPTNO = D.ID\r\n    LEFT OUTER JOIN SCHEDULE (NOLOCK) S\r\n            ON M.ID = S.MEMBERID\r\n           AND S.STARTDATE between $__timeFrom() and $__timeTo()\r\n    LEFT OUTER JOIN DUTY (NOLOCK) W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n          -- AND D.TITLE in($PartNm)\r\n           AND M.MEMBERNM = '$IndivisualNm'\r\n ORDER BY S.STARTDATE DESC"
    }
   ]
  }
 ]
}