{
 "title": "influx dashbord sample",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Host CPU %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "oracle_sysmetric",
     "query": "SELECT \"metric_value\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Host_CPU_Utilization_(%)' AND $timeFilter",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Host_CPU_Utilization_(%)" }
     ]
    }
   ]
  },
  {
   "title": "Session %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "oracle_sysmetric",
     "query": "SELECT \"metric_value\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Session_Limit_%' AND $timeFilter",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Session_Limit_%" }
     ]
    }
   ]
  },
  {
   "title": "Process %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "oracle_sysmetric",
     "query": "SELECT \"metric_value\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Process_Limit_%' AND $timeFilter",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Process_Limit_%" }
     ]
    }
   ]
  },
  {
   "title": "Tablespaces",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tbs_name" ], "type": "tag" }
     ],
     "measurement": "oracle_tablespaces",
     "query": "SELECT last(\"total_space_mb\") AS \"Allocated Space\", last(\"free_space_mb\") AS \"Free Space\", last(\"percent_used\") AS \"Percent Used\", last(\"max_size_mb\") AS \"Max size Autoextend\", last(\"percent_used_autoext\") AS \"Percent Used Autoextend\" FROM \"oracle_tablespaces\" WHERE $timeFilter GROUP BY \"tbs_name\"",
     "select": [
      [
       { "params": [ "total_space_mb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Allocated Space" ], "type": "alias" }
      ],
      [
       { "params": [ "free_space_mb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free Space" ], "type": "alias" }
      ],
      [
       { "params": [ "percent_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Percent Used" ], "type": "alias" }
      ],
      [
       { "params": [ "max_size_mb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Max size Autoextend" ], "type": "alias" }
      ],
      [
       { "params": [ "percent_used_autoext" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Percent Used Autoextend" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oracle Wait Class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_class",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "wait_class" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_wait_class",
     "query": "SELECT mean(\"wait_value\") FROM \"oracle_wait_class\" WHERE $timeFilter GROUP BY time($interval), \"wait_class\" fill(null)",
     "select": [
      [
       { "params": [ "wait_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wait events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Latency" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_wait_event",
     "query": "SELECT mean(\"latency\") AS \"db file sequential read (ms)\", mean(\"count\") AS \"db file sequential read (nb)\" FROM \"oracle_wait_event\" WHERE \"wait_event\" = 'db_file_sequential_read' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "db file sequential read (ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "db file sequential read (nb)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "wait_event", "operator": "=", "value": "db_file_sequential_read" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_wait_event",
     "query": "SELECT mean(\"latency\") AS \"db file scattered read (ms)\", mean(\"count\") AS \"db file scatterred read (nb)\" FROM \"oracle_wait_event\" WHERE \"wait_event\" = 'db_file_scattered_read' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "db file scattered read (ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "db file scatterred read (nb)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "wait_event", "operator": "=", "value": "db_file_scattered_read" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_wait_event",
     "query": "SELECT mean(\"latency\") AS \"log file parallel write (ms)\", mean(\"count\") AS \"log file parallel write (nb)\" FROM \"oracle_wait_event\" WHERE \"wait_event\" = 'log_file_parallel_write' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "log file parallel write (ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "log file parallel write (nb)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "wait_event", "operator": "=", "value": "log_file_parallel_write" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_wait_event",
     "query": "SELECT mean(\"latency\") AS \"log file sync (ms)\", mean(\"count\") AS \"log file sync (nb)\" FROM \"oracle_wait_event\" WHERE \"wait_event\" = 'log_file_sync' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "log file sync (ms)" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "log file sync (nb)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "wait_event", "operator": "=", "value": "log_file_sync" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Usage /s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Host CPU %\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Host_CPU_Utilization_(%)' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Host CPU %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Host_CPU_Utilization_(%)" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"CPU usage cs/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'CPU_Usage_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU usage cs/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "CPU_Usage_Per_Sec" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Host CPU usage cs/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Host_CPU_Usage_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Host CPU usage cs/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Host_CPU_Usage_Per_Sec" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Background CPU usage cs/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Background_CPU_Usage_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Background CPU usage cs/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Background_CPU_Usage_Per_Sec" }
     ]
    }
   ]
  },
  {
   "title": "Physical Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Count/s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Writes/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Writes_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Writes/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Physical_Writes_Per_Sec" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Writes Direct/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Writes_Direct_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Writes Direct/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Physical_Writes_Direct_Per_Sec" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Write IO Rq/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Write_IO_Requests_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Write IO Rq/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "Physical_Write_IO_Requests_Per_Sec"
      }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Writes Direct Lob/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Writes_Direct_Lobs_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Writes Direct Lob/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "Physical_Writes_Direct_Lobs_Per_Sec"
      }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\")  / 1024/1024 AS \"Physical Writes Total MB/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Write_Total_Bytes_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024/1024" ], "type": "math" },
       { "params": [ "Physical Writes Total MB/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "Physical_Write_Total_Bytes_Per_Sec"
      }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\")  / 1024/1024 AS \"Physical Writes MB/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Write_Bytes_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024/1024" ], "type": "math" },
       { "params": [ "Physical Writes MB/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Physical_Write_Bytes_Per_Sec" }
     ]
    }
   ]
  },
  {
   "title": "Physical Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Count/s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Reads/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Reads_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Reads/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Physical_Reads_Per_Sec" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Reads Direct/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Reads_Direct_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Reads Direct/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Physical_Reads_Direct_Per_Sec" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Reads IO Rq/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Read_IO_Requests_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Reads IO Rq/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "Physical_Read_IO_Requests_Per_Sec"
      }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Physical Reads Direct LOB/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Reads_Direct_Lobs_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Physical Reads Direct LOB/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "Physical_Reads_Direct_Lobs_Per_Sec"
      }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") /1024/1024 AS \"Physical Read Total MB/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Read_Total_Bytes_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024/1024" ], "type": "math" },
       { "params": [ "Physical Read Total MB/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "metric_name",
       "operator": "=",
       "value": "Physical_Read_Total_Bytes_Per_Sec"
      }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") /1024/1024 AS \"Physical Read MB/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Physical_Read_Bytes_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024/1024" ], "type": "math" },
       { "params": [ "Physical Read MB/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Physical_Read_Bytes_Per_Sec" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") /1024/1024 AS \"Network MB/s (all clients + dblinks)\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Network_Traffic_Volume_Per_Sec' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024/1024" ], "type": "math" },
       {
        "params": [
         "Network MB/s (all clients + dblinks)"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Network_Traffic_Volume_Per_Sec" }
     ]
    }
   ]
  },
  {
   "title": "Redo",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Count/s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") /1024/1024 AS \"Redo MB/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Redo_Generated_Per_Sec' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1024/1024" ], "type": "math" },
       { "params": [ "Redo MB/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Redo_Generated_Per_Sec" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Redo Writes/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Redo_Writes_Per_Sec' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Redo Writes/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Redo_Writes_Per_Sec" }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Average Active Sessions\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Average_Active_Sessions' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average Active Sessions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Average_Active_Sessions" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Session Count\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Session_Count' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Session Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Session_Count" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Session Limit %\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Session_Limit_%' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Session Limit %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Session_Limit_%" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_sysmetric",
     "query": "SELECT mean(\"metric_value\") AS \"Logons/s\" FROM \"oracle_sysmetric\" WHERE \"metric_name\" = 'Logons_Per_Sec' AND $timeFilter GROUP BY time($interval), \"metric_name\" fill(null)",
     "select": [
      [
       { "params": [ "metric_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Logons/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "metric_name", "operator": "=", "value": "Logons_Per_Sec" }
     ]
    }
   ]
  }
 ]
}