{
 "title": "Monitoring Server Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "[DiskUsage] Monitoring Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dba\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"LPSQLMON\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> group(columns: [\"host\", \"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  // |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r._field, device:r.device}))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "[DiskIO] Monitoring Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"dba\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"LPSQLMON\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_time\")\r\n  // |> filter(fn: (r) => r[\"name\"] == \"D:\")\r\n  // |> group(columns: [\"host\", \"name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  // |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r._field, name:r.name}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"derivative\")"
    },
    {
     "query": "from(bucket: \"dba\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"LPSQLMON\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_time\")\r\n  // |> filter(fn: (r) => r[\"name\"] == \"D:\")\r\n  // |> group(columns: [\"host\", \"name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  // |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r._field, name:r.name}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "[CPU] Monitoring Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"dba\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"LPSQLMON\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:100.0 - r._value, _time:r._time, _field:r.host}))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "[Memory] Monitoring Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"dba\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"LPSQLMON\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  // |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.host}))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "WhoisActive count", "type": "timeseries", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 } },
  { "title": "푸드1 CXPacket Count", "type": "timeseries", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 } }
 ]
}