{
 "title": "realtime mssql locktree",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PartName",
    "query": "SELECT 'MD' AS PartName\nUNION\nSELECT '마케팅' AS PartName\nUNION\nSELECT '경영지원' AS PartName\nUNION\nSELECT '재무' AS PartName\nUNION\nSELECT 'POS' AS PartName\nUNION\nSELECT '상품권' AS PartName\nUNION\nSELECT '인프라' AS PartName"
   },
   {
    "name": "ServerName",
    "query": "usp_get_DBA_Target_Svr 'row', \"$PartName\""
   },
   { "name": "CollectDate", "label": "수집일시", "query": "2023-10-26 10:33:05.400" },
   { "name": "session_id", "label": "세션아이디", "query": "179" }
  ]
 },
 "panels": [
  {
   "title": "Lock Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "select d.CollectDate as time, isnull(z.cnt,0) as cnt\r\n  from (select distinct dtm.CollectDate\r\n             , i.InstanceID\r\n          from TBL2_M_WhoIsActive dtm, META2_M_InstanceInfo i (nolock)\r\n         where i.InstanceID = dtm.InstanceID\r\n           and dtm.CollectDate between $__timeFrom() AND $__timeTo()\r\n           and i.ServerName = ${ServerName:singlequote}\r\n       ) d\r\nleft outer join \r\n       (select CollectDate, w.InstanceID\r\n             , count(distinct w.session_id) as cnt\r\n          from META2_M_InstanceInfo i (nolock), TBL2_M_WhoIsActive w (nolock)\r\n         where i.InstanceID = w.InstanceID\r\n           and w.CollectDate between $__timeFrom() AND $__timeTo()\r\n           and w.blocking_session_id > 0\r\n           and i.ServerName = ${ServerName:singlequote}\r\n        group by w.CollectDate, w.InstanceID\r\n       ) z \r\n      on d.InstanceID = z.InstanceID\r\n     and d.CollectDate = z.CollectDate\r\n where d.CollectDate between $__timeFrom() AND $__timeTo()\r\norder by time"
    }
   ]
  },
  {
   "title": "Lock count table in time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "select convert(char(23),z.CollectDate,21) as CollectDate, isnull(z.cnt,0) as cnt\r\n  from (select CollectDate, w.InstanceID\r\n             , count(distinct w.session_id) as cnt\r\n          from META2_M_InstanceInfo i (nolock), TBL2_M_WhoIsActive w (nolock)\r\n         where i.InstanceID = w.InstanceID\r\n           and w.CollectDate between $__timeFrom() AND $__timeTo()\r\n           and w.blocking_session_id > 0\r\n           and i.ServerName = ${ServerName:singlequote}\r\n        group by w.CollectDate, w.InstanceID\r\n       ) z \r\norder by CollectDate DESC"
    }
   ]
  },
  {
   "title": "Lock Tree (WAIT INFO)",
   "type": "equansdatahub-tree-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "with data_set as (\r\nselect session_id, case when blocking_session_id = session_id then null else blocking_session_id end blocking_session_id, lock_status \r\n  from (select w.session_id, case when w.blocking_session_id = 0 then null else  w.blocking_session_id end blocking_session_id, \r\n               '[' + convert(varchar,w.session_id) + ': ' + status +'] ' +  wait_info as lock_status\r\n            -- , w.total_elapsed_time as elapsed_time\r\n             , row_number() over(partition by w.CollectDate, w.session_id, w.blocking_session_id order by w.total_elapsed_time desc) rnk\r\n         from META2_M_InstanceInfo i with (nolock), TBL2_M_WhoIsActive w with (nolock)\r\n        where i.InstanceID = w.InstanceID\r\n          and sql_text <> 'sp_server_diagnostics'\r\n          and i.ServerName IN (${ServerName:singlequote})\r\n          and CollectDate = ${CollectDate:singlequote}\r\n       ) z\r\n where rnk = 1\r\n ) \r\nselect session_id\r\n     , (select session_id from data_set c  with (nolock) where a.blocking_session_id = c.session_id) blocking_session_id\r\n     , lock_status\r\n from data_set a"
    }
   ]
  },
  {
   "title": "Lock Tree (SQL INFO)",
   "type": "equansdatahub-tree-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "with data_set as (\r\nselect session_id, case when blocking_session_id = session_id then null else blocking_session_id end blocking_session_id, sql_text \r\n  from (select w.session_id, case when w.blocking_session_id = 0 then null else  w.blocking_session_id end blocking_session_id, \r\n               '[' + convert(varchar,w.session_id) + '] ' + case when w.ObjectName= '' then w.sql_text \r\n                    else  + w.ObjectName \r\n                end sql_text\r\n            -- , w.total_elapsed_time as elapsed_time\r\n             , row_number() over(partition by w.CollectDate, w.session_id, w.blocking_session_id order by w.total_elapsed_time desc) rnk\r\n         from META2_M_InstanceInfo i with (nolock), TBL2_M_WhoIsActive w with (nolock)\r\n        where i.InstanceID = w.InstanceID\r\n          and sql_text <> 'sp_server_diagnostics'\r\n          and i.ServerName IN (${ServerName:singlequote})\r\n          and CollectDate = ${CollectDate:singlequote}\r\n       ) z\r\n where rnk = 1\r\n ) \r\nselect session_id\r\n     , (select session_id from data_set c  with (nolock) where a.blocking_session_id = c.session_id) blocking_session_id\r\n     , sql_text\r\n from data_set a"
    }
   ]
  },
  {
   "title": "Locked Session (INFO Detail)⏰",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "select column_name, column_value from (\r\nselect *\r\n  from (select convert(nvarchar(4000),session_id)                   as session_id\r\n             , convert(nvarchar(4000),tran_start_time, 121)         as tran_start_time\r\n             , convert(nvarchar(4000),total_elapsed_time)           as total_elapsed_time\r\n             , convert(nvarchar(4000),login_name)                   as login_name\r\n             , convert(nvarchar(4000),host_name)                    as host_name\r\n             , convert(nvarchar(4000),open_tran_count)              as open_tran_count\r\n             , convert(nvarchar(4000),transaction_isolation_level)  as transaction_isolation_level\r\n             , convert(nvarchar(4000),program_name)                 as program_name\r\n             , convert(nvarchar(4000),wait_info)                    as wait_info\r\n             , convert(nvarchar(4000),cpu)                          as cpu\r\n             , convert(nvarchar(4000),reads)                        as reads\r\n             , convert(nvarchar(4000),tempdb_allocations)           as tempdb_allocations\r\n             , convert(nvarchar(4000),physical_reads)               as physical_reads\r\n             , convert(nvarchar(4000),case when objectname = ''  then sql_text else objectname end) as sql_text\r\n             , convert(nvarchar(4000),query_hash, 1)                as query_hash\r\n             , convert(nvarchar(4000),query_plan_hash, 1)           as query_plan_hash\r\n             , ROW_NUMBER() over(partition by session_id order by total_elapsed_time desc) rnk\r\n           from META2_M_InstanceInfo i with (nolock)\r\n              , TBL2_M_WhoIsActive w with (nolock)\r\n          where i.InstanceID = w.InstanceID\r\n            and sql_text <> 'sp_server_diagnostics'\r\n            and i.ServerName = ${ServerName:singlequote}\r\n            and CollectDate = ${CollectDate:singlequote}\r\n            and w.session_id = ${session_id}\r\n       ) z\r\n where rnk = 1\r\n ) z\r\n  unpivot(column_value for column_name in  (session_id, tran_start_time, total_elapsed_time, login_name, host_name, program_name,\r\n                                     open_tran_count, transaction_isolation_level, wait_info, cpu, reads, tempdb_allocations,\r\n                                     physical_reads, sql_text, query_hash, query_plan_hash)) as unp\r\n"
    }
   ]
  },
  {
   "title": "Blocking Session (INFO Detail)🔒",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "select link_session_id, column_name, column_value from (\r\nselect *\r\n  from (select convert(nvarchar(4000),b.session_id)                   as link_session_id\r\n             , convert(nvarchar(4000),b.session_id)                   as session_id\r\n             , convert(nvarchar(4000),b.tran_start_time, 121)         as tran_start_time\r\n             , convert(nvarchar(4000),b.total_elapsed_time)           as total_elapsed_time\r\n             , convert(nvarchar(4000),b.login_name)                   as login_name\r\n             , convert(nvarchar(4000),b.host_name)                    as host_name\r\n             , convert(nvarchar(4000),b.open_tran_count)              as open_tran_count\r\n             , convert(nvarchar(4000),b.transaction_isolation_level)  as transaction_isolation_level\r\n             , convert(nvarchar(4000),b.program_name)                 as program_name\r\n             , convert(nvarchar(4000),b.wait_info)                    as wait_info\r\n             , convert(nvarchar(4000),b.cpu)                          as cpu\r\n             , convert(nvarchar(4000),b.reads)                        as reads\r\n             , convert(nvarchar(4000),b.tempdb_allocations)           as tempdb_allocations\r\n             , convert(nvarchar(4000),b.physical_reads)               as physical_reads\r\n             , convert(nvarchar(4000),case when b.objectname = ''  then b.sql_text else b.objectname end) as sql_text\r\n             , convert(nvarchar(4000),b.query_hash, 1)                as query_hash\r\n             , convert(nvarchar(4000),b.query_plan_hash, 1)           as query_plan_hash\r\n             , ROW_NUMBER() over(partition by b.session_id order by b.total_elapsed_time desc) rnk\r\n           from META2_M_InstanceInfo i with (nolock)\r\n              , TBL2_M_WhoIsActive w\r\n              , TBL2_M_WhoIsActive b\r\n          where i.InstanceID = w.InstanceID\r\n            and w.sql_text <> 'sp_server_diagnostics'\r\n            and b.sql_text <> 'sp_server_diagnostics'\r\n            and i.ServerName = ${ServerName:singlequote}\r\n            and w.CollectDate = ${CollectDate:singlequote}\r\n            and b.CollectDate = ${CollectDate:singlequote}\r\n            and w.session_id = ${session_id}\r\n            and i.InstanceID = b.InstanceID\r\n            and w.blocking_session_id = b.session_id\r\n       ) z\r\n where rnk = 1\r\n ) z\r\n  unpivot(column_value for column_name in  (session_id, tran_start_time, total_elapsed_time, login_name, host_name, program_name,\r\n                                     open_tran_count, transaction_isolation_level, wait_info, cpu, reads, tempdb_allocations,\r\n                                     physical_reads, sql_text, query_hash, query_plan_hash)) as unp"
    }
   ]
  }
 ]
}