{
 "title": "monthly check oracle tablespace",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "영업통합 DB Space(GB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "rawSql": "select substring(b.sid,1,length(b.sid)-1) as db_name, \r\n       time,\r\n       round(sum(total_space)/1024.0,2) as total_GB\r\n-- owner can be alternative\r\n  from lpsis1.ora_tablespace_info a, apm_db_info b\r\n where 1=1\r\n-- range has to be changed monthly\r\n   and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' + interval '1 months' \r\n   and a.db_id = b.db_id\r\ngroup by b.sid,time\r\n"
    },
    {
     "rawSql": "select substring(b.sid,1,length(b.sid)-1) as db_name, \r\n       time,\r\n       round((sum(total_space) - sum(free_space) )  /1024.0,2) as used_GB\r\n-- owner can be alternative\r\n  from lpsis1.ora_tablespace_info a, apm_db_info b\r\n where 1=1\r\n-- range has to be changed monthly\r\n   and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' + interval '1 months' \r\n   and a.db_id = b.db_id\r\ngroup by b.sid,time\r\n"
    }
   ]
  },
  {
   "title": "영업통합 LPSIS_DATA(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select substring(b.sid,1,length(b.sid)-1) as db_name, \r\n       time,\r\n       sum(usage) as \"use(%)\"\r\n-- owner can be alternative\r\n  from lpsis1.ora_asm_disk_group_info a, apm_db_info b\r\n where 1=1\r\n-- range has to be changed monthly\r\n   and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' + interval '1 months' \r\n   and a.db_id = b.db_id\r\n   and a.group_name = 'LPSIS_DATA'\r\ngroup by b.sid,time\r\n"
    }
   ]
  },
  {
   "title": "배치 DB Space(GB)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "rawSql": "\r\n\r\nselect DBNAME, convert(date,COLLECTDT) time, SUM(TOT_GB) TOT_GB\r\nfrom[dbo].[TB_Ora_Tbs_Chk_L]\r\nwhere 1=1\r\nAND dbname ='LPCTR'\r\nAND collectdt Between REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nGROUP BY DBNAME, COLLECTDT\r\nORDER BY 2\r\n"
    },
    {
     "rawSql": "\r\n\r\nselect DBNAME, convert(date,COLLECTDT) time, SUM(USE_GB) USE_GB\r\nfrom[dbo].[TB_Ora_Tbs_Chk_L]\r\nwhere 1=1\r\nAND dbname ='LPCTR'\r\nAND collectdt Between REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nGROUP BY DBNAME, COLLECTDT\r\nORDER BY 2\r\n"
    }
   ]
  },
  {
   "title": "배치 DB Space(GB) TSD_EZMNA_N1 상세모니터링",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "rawSql": "\r\n\r\nselect DBNAME, convert(date,COLLECTDT) time, SUM(TOT_GB) TOT_GB\r\nfrom[dbo].[TB_Ora_Tbs_Chk_L]\r\nwhere 1=1\r\nAND dbname ='LPCTR'\r\nAND TBS_NAME = 'TSD_EZMNA_N1'\r\nAND collectdt Between REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nGROUP BY DBNAME, COLLECTDT\r\nORDER BY 2\r\n"
    },
    {
     "rawSql": "\r\n\r\nselect DBNAME, convert(date,COLLECTDT) time, SUM(USE_GB) USE_GB\r\nfrom[dbo].[TB_Ora_Tbs_Chk_L]\r\nwhere 1=1\r\nAND dbname ='LPCTR'\r\nAND TBS_NAME = 'TSD_EZMNA_N1'\r\nAND collectdt Between REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nGROUP BY DBNAME, COLLECTDT\r\nORDER BY 2\r\n"
    }
   ]
  },
  {
   "title": "인사 DB Space(GB)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "rawSql": "select substring(b.sid,1,length(b.sid)-1) as db_name, \r\n       time,\r\n       round(sum(total_space)/1024.0,2) as total_GB\r\n-- owner can be alternative\r\n  from lottehrs1.ora_tablespace_info a, apm_db_info b\r\n where 1=1\r\n-- range has to be changed monthly\r\n   and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' + interval '1 months' \r\n   and a.db_id = b.db_id\r\ngroup by b.sid,time\r\n"
    },
    {
     "rawSql": "select substring(b.sid,1,length(b.sid)-1) as db_name, \r\n       time,\r\n       round((sum(total_space) - sum(free_space) )  /1024.0,2) as used_GB\r\n-- owner can be alternative\r\n  from lottehrs1.ora_tablespace_info a, apm_db_info b\r\n where 1=1\r\n-- range has to be changed monthly\r\n   and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' + interval '1 months' \r\n   and a.db_id = b.db_id\r\ngroup by b.sid,time\r\n"
    }
   ]
  },
  {
   "title": "배송 DB Space(GB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "rawSql": "\r\n\r\nselect DBNAME, convert(date,COLLECTDT) time, SUM(TOT_GB) TOT_GB\r\nfrom[dbo].[TB_Ora_Tbs_Chk_L]\r\nwhere 1=1\r\nAND dbname ='LPDLV'\r\nAND collectdt Between REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nGROUP BY DBNAME, COLLECTDT\r\nORDER BY 2\r\n"
    },
    {
     "rawSql": "\r\n\r\nselect DBNAME, convert(date,COLLECTDT) time, SUM(USE_GB) USE_GB\r\nfrom[dbo].[TB_Ora_Tbs_Chk_L]\r\nwhere 1=1\r\nAND dbname ='LPDLV'\r\nAND collectdt Between REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nGROUP BY DBNAME, COLLECTDT\r\nORDER BY 2"
    }
   ]
  }
 ]
}