{
 "title": "monthly check oracle resource",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TimeRangeGroup",
    "query": "SELECT CASE WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) < 1*60*24 THEN 1\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) BETWEEN  1*60*24 AND   2*60*24 AND DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) <> 2  *60*24 THEN 30\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) BETWEEN  2*60*24 AND  30*60*24 AND DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) <> 30 *60*24 THEN 60\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) BETWEEN 30*60*24 AND 365*60*24 AND DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) <> 365*60*24 THEN 180\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) >= 365*60*24 THEN 720\n        END"
   }
  ]
 },
 "panels": [
  {
   "title": "영업통합 CPU Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": " SELECT date_trunc('hour',s.time) + (((extract(minute FROM s.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n      -- , trunc(max_value/100) AS lpsis1_max\r\n      , trunc(MAX(avg_value/100)) AS lpsis1_CPU\r\n      -- extract(hour from date_trunc('hour', TO_TIMESTAMP(floor(extract(epoch from s.time)/3600)*3600)))\r\n   FROM lpsis1.apm_db_os_stat_10min s,ora_db_os_name n\r\n  WHERE s.db_id = n.db_id\r\n    AND s.os_id = n.os_id\r\n    AND n.os_id = 6\r\n    and s.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS'))  + interval '1 months' \r\ngroup by 1\r\norder by 1"
    },
    {
     "rawSql": " SELECT date_trunc('hour',s.time) + (((extract(minute FROM s.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n      -- , trunc(max_value/100) AS lpsis1_max\r\n      , trunc(MAX(avg_value/100)) AS lpsis2_CPU\r\n      -- extract(hour from date_trunc('hour', TO_TIMESTAMP(floor(extract(epoch from s.time)/3600)*3600)))\r\n   FROM lpsis2.apm_db_os_stat_10min s,ora_db_os_name n\r\n  WHERE s.db_id = n.db_id\r\n    AND s.os_id = n.os_id\r\n    AND n.os_id = 6\r\n    and s.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS'))  + interval '1 months' \r\ngroup by 1\r\norder by 1"
    }
   ]
  },
  {
   "title": "영업통합 Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour',a.time) + (((extract(minute FROM a.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n     , ROUND(MAX(( ROUND(  a.max_value/1024.0 , 1 ) -  ROUND( b.avg_value /1024.0 , 1 ) ) /ROUND(  a.max_value/1024.0 , 1 ) *100.0) , 0 ) AS lpsis1_Mem_Use\r\n   FROM lpsis1.apm_db_os_stat_10min a, lpsis1.apm_db_os_stat_10min b, ora_db_os_name c\r\n  WHERE a.db_id = c.db_id\r\n    AND a.os_id = c.os_id\r\n    and a.partition_key  = b.partition_key\r\n    AND c.os_id = 5\r\n    and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) + interval '1 months' \r\n    and a.time = b.time\r\n    and a.db_id = b.db_id\r\n    and b.os_id = 4\r\ngroup by 1\r\norder by 1\r\n;"
    },
    {
     "rawSql": "SELECT date_trunc('hour',a.time) + (((extract(minute FROM a.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n     , ROUND(MAX(( ROUND(  a.max_value/1024.0 , 1 ) -  ROUND( b.avg_value /1024.0 , 1 ) ) /ROUND(  a.max_value/1024.0 , 1 ) *100.0) , 0 ) AS lpsis2_Mem_Use\r\n   FROM lpsis2.apm_db_os_stat_10min a, lpsis2.apm_db_os_stat_10min b, ora_db_os_name c\r\n  WHERE a.db_id = c.db_id\r\n    AND a.os_id = c.os_id\r\n    and a.partition_key  = b.partition_key\r\n    AND c.os_id = 5\r\n    and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) + interval '1 months' \r\n    and a.time = b.time\r\n    and a.db_id = b.db_id\r\n    and b.os_id = 4\r\ngroup by 1\r\norder by 1\r\n;"
    }
   ]
  },
  {
   "title": "배치 CPU Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) AS time\r\n     , MAX(cpuUse) AS lpctr1_CPU_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpbatap01'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by time"
    },
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) AS time\r\n     , MAX(cpuUse) AS lpctr2_CPU_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpbatap02'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by time"
    }
   ]
  },
  {
   "title": "배치 Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) AS time\r\n     , MAX(memUse) AS lpctr1_Mem_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpbatap01'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by 1"
    },
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) AS time\r\n     , MAX(memUse) lpctr2_Mem_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpbatap02'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by 1"
    }
   ]
  },
  {
   "title": "인사 CPU Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": " SELECT date_trunc('hour',s.time) + (((extract(minute FROM s.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n      -- , trunc(max_value/100) AS lottehrs1_max\r\n      , trunc(MAX(avg_value/100)) AS lottehrs1_CPU\r\n      -- extract(hour from date_trunc('hour', TO_TIMESTAMP(floor(extract(epoch from s.time)/3600)*3600)))\r\n   FROM lottehrs1.apm_db_os_stat_10min s,ora_db_os_name n\r\n  WHERE s.db_id = n.db_id\r\n    AND s.os_id = n.os_id\r\n    AND n.os_id = 6\r\n    and s.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS'))  + interval '1 months' \r\ngroup by 1\r\norder by 1"
    },
    {
     "rawSql": "  SELECT date_trunc('hour',s.time) + (((extract(minute FROM s.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n      -- , trunc(max_value/100) AS lottehrs2_max\r\n      , trunc(MAX(avg_value/100)) AS lottehrs2_CPU\r\n      -- extract(hour from date_trunc('hour', TO_TIMESTAMP(floor(extract(epoch from s.time)/3600)*3600)))\r\n   FROM lottehrs2.apm_db_os_stat_10min s,ora_db_os_name n\r\n  WHERE s.db_id = n.db_id\r\n    AND s.os_id = n.os_id\r\n    AND n.os_id = 6\r\n    and s.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS'))  + interval '1 months' \r\ngroup by 1\r\norder by 1"
    }
   ]
  },
  {
   "title": "인사 Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour',a.time) + (((extract(minute FROM a.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n     , ROUND(MAX(( ROUND(  a.max_value/1024.0 , 1 ) -  ROUND( b.avg_value /1024.0 , 1 ) ) /ROUND(  a.max_value/1024.0 , 1 ) *100.0) , 0 ) AS lottehrs1_Mem_Use\r\n   FROM lottehrs1.apm_db_os_stat_10min a, lottehrs1.apm_db_os_stat_10min b, ora_db_os_name c\r\n  WHERE a.db_id = c.db_id\r\n    AND a.os_id = c.os_id\r\n    and a.partition_key  = b.partition_key\r\n    AND c.os_id = 5\r\n    and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) + interval '1 months' \r\n    and a.time = b.time\r\n    and a.db_id = b.db_id\r\n    and b.os_id = 4\r\ngroup by 1\r\norder by 1\r\n;"
    },
    {
     "rawSql": "SELECT date_trunc('hour',a.time) + (((extract(minute FROM a.time)::int / $TimeRangeGroup) * $TimeRangeGroup)::text || ' minute')::interval as time\r\n     , ROUND(MAX(( ROUND(  a.max_value/1024.0 , 1 ) -  ROUND( b.avg_value /1024.0 , 1 ) ) /ROUND(  a.max_value/1024.0 , 1 ) *100.0) , 0 ) AS lottehrs2_Mem_Use\r\n   FROM lottehrs2.apm_db_os_stat_10min a, lottehrs2.apm_db_os_stat_10min b, ora_db_os_name c\r\n  WHERE a.db_id = c.db_id\r\n    AND a.os_id = c.os_id\r\n    AND c.os_id = 5\r\n    and a.time between date_trunc('month', to_date($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS')) - interval '0 months' and date_trunc('month', to_date($__timeTo(),'YYYY-MM-DDTHH24:MI:SS')) + interval '1 months' \r\n    and a.time = b.time\r\n    and a.db_id = b.db_id\r\n    and b.os_id = 4\r\ngroup by 1\r\norder by 1\r\n;"
    }
   ]
  },
  {
   "title": "배송 CPU Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) AS time\r\n     , MAX(cpuUse) AS lpdlvdb01_CPU_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpdlvdb01'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by 1"
    },
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) as time\r\n     , MAX(cpuUse) AS lpdlvdb02_CPU_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpdlvdb02'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by 1"
    }
   ]
  },
  {
   "title": "배송 Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) as time\r\n     , MAX(memUse) AS lpdlvdb01_Mem_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpdlvdb01'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by 1"
    },
    {
     "rawSql": "SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0) as time\r\n     , MAX(memUse) AS lpdlvdb02_Mem_Use\r\n   from [dbo].[TB_Svr_Rsrc_Chk_L]\r\n  where 1=1\r\n    and hostname = 'lpdlvdb02'\r\n    AND collectdt BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\ngroup by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, RGST_DTM) / $TimeRangeGroup * $TimeRangeGroup, 0)\r\norder by 1"
    }
   ]
  }
 ]
}