{
 "title": "monthly check mssql storage",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PartName",
    "query": "SELECT 'MD' AS PartName\nUNION\nSELECT '마케팅' AS PartName\nUNION\nSELECT '경영지원' AS PartName\nUNION\nSELECT '재무' AS PartName\nUNION\nSELECT 'POS' AS PartName\nUNION\nSELECT '상품권' AS PartName\nUNION\nSELECT '인프라' AS PartName"
   },
   {
    "name": "ServerName",
    "query": "usp_get_DBA_Target_Svr 'row', \"$PartName\""
   },
   {
    "name": "TimeRangeGroup",
    "query": "SELECT CASE WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) < 1*60*24 THEN 1\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) BETWEEN  1*60*24 AND   2*60*24 AND DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) <> 2  *60*24 THEN 30\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) BETWEEN  2*60*24 AND  30*60*24 AND DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) <> 30 *60*24 THEN 60\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) BETWEEN 30*60*24 AND 365*60*24 AND DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) <> 365*60*24 THEN 180\n            WHEN DATEDIFF(MINUTE, $__timeFrom(), $__timeTo()) >= 365*60*24 THEN 720\n        END"
   }
  ]
 },
 "panels": [
  {
   "title": "MS-SQL Disk Use_Pct",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "    DECLARE @Text VARCHAR(MAX) = ''\r\n    DECLARE @sSQL VARCHAR(MAX) = ''\r\n    DECLARE @nSQL nVARCHAR(MAX) = ''\r\n\r\n\r\n    IF OBJECT_ID('tempdb..#TempResult') IS NOT NULL\r\n        DROP TABLE #TempResult \r\n\r\n    CREATE TABLE #TempResult(\r\n          time datetime\r\n        , SVR_Drive nvarchar(20)\r\n        , DiskUtilization decimal(5,2)\r\n    )\r\n\r\n    INSERT INTO #TempResult (time, SVR_Drive, DiskUtilization)\r\n    SELECT \r\n      DATEADD(MINUTE, DATEDIFF(MINUTE, 0, dku.CollectDate) / $TimeRangeGroup * $TimeRangeGroup, 0) AS time\r\n      , ins.ServerName+ ' '+ CASE WHEN dku.Drive LIKE '\\\\%' THEN 'NAS' ELSE dku.Drive END AS [SVR_Drive]\r\n      , ISNULL (MAX(CONVERT(decimal(5, 2), ROUND((ISNULL(dku.TotalSpaceMB,dt.TotalSpaceMB) - dku.FreeSpaceMB) / ISNULL(dku.TotalSpaceMB,dt.TotalSpaceMB) *100, 2))), 0) AS [DiskUtilization]\r\n    FROM [dbo].[META2_M_InstanceInfo] AS ins \r\n    INNER JOIN [dbo].[TBL2_M_DatabaseDiskUsage] AS dku ON ins.InstanceID = dku.InstanceID\r\n INNER JOIN (\r\n\t\t\tSELECT T1.InstanceID\r\n\t\t\t      ,T1.Drive\r\n\t\t\t  FROM [TBL2_M_DatabaseDiskUsage] T1\r\n\t\t\t      ,(\r\n\t\t\t\t      SELECT InstanceID\r\n\t\t\t\t\t\t        ,MAX(CollectDate) AS CollectDate\r\n\t\t\t\t\t    FROM [TBL2_M_DatabaseDiskUsage]\r\n\t\t\t\t\t   WHERE 1=1\r\n\t\t\t\t\t     AND $__timeFilter(CollectDate)\r\n\t\t\t\t\t   GROUP BY InstanceID\r\n\t\t\t\t   ) T2\r\n\t\t\t WHERE T1.InstanceID = T2.InstanceID\r\n\t\t\t   AND T1.CollectDate = T2.CollectDate\r\n\t\t\t GROUP BY T1.InstanceID, T1.Drive\r\n\t       ) AS dku2\r\n\t  ON dku2.InstanceID = dku.InstanceID AND dku2.Drive = dku.Drive    \r\n    LEFT JOIN (\r\n      SELECT 'F:\\' AS Drive, 409597 AS TotalSpaceMB\r\n      UNION ALL\r\n      SELECT 'G:\\' AS Drive, 153597 AS TotalSpaceMB\r\n    ) dt ON dku.Drive = dt.Drive AND dku.InstanceID = 21\t\t\t\t\r\n    WHERE ins.UseYN = 'Y'\r\n  \tAND ins.ServerName IN($ServerName)\r\n  \tAND $__timeFilter(dku.CollectDate) \r\n  \tAND dku.CollectDate > CONVERT(VARCHAR(10), DATEADD(YEAR, -3, GETDATE()), 121)\r\n    GROUP BY DATEADD(MINUTE, DATEDIFF(MINUTE, 0, dku.CollectDate) / $TimeRangeGroup * $TimeRangeGroup, 0), ins.ServerName, dku.Drive\r\n\r\n    SELECT @TEXT = STUFF((SELECT DISTINCT ',\"' + SVR_Drive +'\"'\r\n                            FROM #TempResult\r\n                          ORDER BY 1 DESC\r\n                          FOR XML PATH('')),1,1,'')\r\n\r\n    SET @sSQL += '\r\n        SELECT * \r\n          FROM #TempResult\r\n         PIVOT (MAX(DiskUtilization) FOR SVR_Drive IN (' + @TEXT + ')) AS PVT\r\n         ORDER BY 1'\r\n\r\n\r\n    SET @nSQL = @sSQL\r\n\r\n    EXEC SP_EXECUTESQL @nSQL"
    }
   ]
  },
  {
   "title": "MS-SQL Disk Use_Pct",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "rawSql": "    DECLARE @Text VARCHAR(MAX) = ''\r\n    DECLARE @sSQL VARCHAR(MAX) = ''\r\n    DECLARE @nSQL nVARCHAR(MAX) = ''\r\n\r\n\r\n    IF OBJECT_ID('tempdb..#TempResult') IS NOT NULL\r\n        DROP TABLE #TempResult \r\n\r\n    CREATE TABLE #TempResult(\r\n          time datetime\r\n        , SVR_Drive nvarchar(20)\r\n        , DiskUtilization INT\r\n    )\r\n\r\n    INSERT INTO #TempResult (time, SVR_Drive, DiskUtilization)\r\n    SELECT \r\n      DATEADD(MINUTE, DATEDIFF(MINUTE, 0, dku.CollectDate) / $TimeRangeGroup * $TimeRangeGroup, 0) AS time\r\n      , ins.ServerName+ ' '+ CASE WHEN dku.Drive LIKE '\\\\%' THEN 'NAS' ELSE dku.Drive END AS [SVR_Drive]\r\n      , ISNULL (MAX(ISNULL(dku.TotalSpaceMB,dt.TotalSpaceMB) - dku.FreeSpaceMB), 0) AS [DiskUtilization]\r\n    FROM [dbo].[META2_M_InstanceInfo] AS ins \r\n    INNER JOIN [dbo].[TBL2_M_DatabaseDiskUsage] AS dku ON ins.InstanceID = dku.InstanceID\r\n INNER JOIN (\r\n\t\t\tSELECT T1.InstanceID\r\n\t\t\t      ,T1.Drive\r\n\t\t\t  FROM [TBL2_M_DatabaseDiskUsage] T1\r\n\t\t\t      ,(\r\n\t\t\t\t      SELECT InstanceID\r\n\t\t\t\t\t\t        ,MAX(CollectDate) AS CollectDate\r\n\t\t\t\t\t    FROM [TBL2_M_DatabaseDiskUsage]\r\n\t\t\t\t\t   WHERE 1=1\r\n\t\t\t\t\t     AND $__timeFilter(CollectDate)\r\n\t\t\t\t\t   GROUP BY InstanceID\r\n\t\t\t\t   ) T2\r\n\t\t\t WHERE T1.InstanceID = T2.InstanceID\r\n\t\t\t   AND T1.CollectDate = T2.CollectDate\r\n\t\t\t GROUP BY T1.InstanceID, T1.Drive\r\n\t       ) AS dku2\r\n\t  ON dku2.InstanceID = dku.InstanceID AND dku2.Drive = dku.Drive    \r\n    LEFT JOIN (\r\n      SELECT 'F:\\' AS Drive, 409597 AS TotalSpaceMB\r\n      UNION ALL\r\n      SELECT 'G:\\' AS Drive, 153597 AS TotalSpaceMB\r\n    ) dt ON dku.Drive = dt.Drive AND dku.InstanceID = 21\t\t\t\t\r\n    WHERE ins.UseYN = 'Y'\r\n  \tAND ins.ServerName IN($ServerName)\r\n  \tAND $__timeFilter(dku.CollectDate) \r\n  \tAND dku.CollectDate > CONVERT(VARCHAR(10), DATEADD(YEAR, -3, GETDATE()), 121)\r\n    GROUP BY DATEADD(MINUTE, DATEDIFF(MINUTE, 0, dku.CollectDate) / $TimeRangeGroup * $TimeRangeGroup, 0), ins.ServerName, dku.Drive\r\n\r\n    SELECT @TEXT = STUFF((SELECT DISTINCT ',\"' + SVR_Drive +'\"'\r\n                            FROM #TempResult\r\n                          ORDER BY 1 DESC\r\n                          FOR XML PATH('')),1,1,'')\r\n\r\n    SET @sSQL += '\r\n        SELECT * \r\n          FROM #TempResult\r\n         PIVOT (MAX(DiskUtilization) FOR SVR_Drive IN (' + @TEXT + ')) AS PVT\r\n         ORDER BY 1'\r\n\r\n\r\n    SET @nSQL = @sSQL\r\n\r\n    EXEC SP_EXECUTESQL @nSQL"
    }
   ]
  },
  {
   "title": "MS-SQL Storage Usage(Data, GB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "rawSql": "SELECT B.CollectDate as time\r\n\t , A.ServerName +'  ' + B.databaseName as databaseName\r\n\t , B.TotalSizeMB/1024 as TotalSizeMB\r\n  FROM [MonitoringDB].[dbo].[META2_M_InstanceInfo]  A\r\n INNER JOIN [MonitoringDB].[dbo].[TB_DataSizeGrowth_S] B \r\n    ON A.InstanceID = B.instanceID\r\n INNER JOIN (\r\n\t\t\tSELECT T1.InstanceID\r\n\t\t\t      ,T1.databaseName\r\n\t\t\t  FROM [TBL2_M_DatabaseDiskUsage] T1\r\n\t\t\t      ,(\r\n\t\t\t\t      SELECT InstanceID\r\n\t\t\t\t\t\t        ,MAX(CollectDate) AS CollectDate\r\n\t\t\t\t\t    FROM [TBL2_M_DatabaseDiskUsage]\r\n\t\t\t\t\t   WHERE 1=1\r\n\t\t\t\t\t     AND $__timeFilter(CollectDate) \r\n\t\t\t\t\t   GROUP BY InstanceID\r\n\t\t\t\t   ) T2\r\n\t\t\t WHERE T1.InstanceID = T2.InstanceID\r\n\t\t\t   AND T1.CollectDate = T2.CollectDate\r\n\t\t\t GROUP BY T1.InstanceID, T1.databaseName\r\n\t       ) dku2\r\n\t\tON dku2.InstanceID = B.InstanceID AND dku2.databaseName = B.databaseName\r\n WHERE B.databaseName NOT IN ('master','tempdb','model','msdb')\r\n   AND a.ServerName IN ($ServerName)\r\n   AND $__timeFilter(B.CollectDate) \r\n   AND A.UseYN = 'Y'\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT B.CollectDate as time\r\n\t , A.ServerName +'  ' + B.databaseName as databaseName\r\n\t , B.UsedSizeMB/1024 as UsedSizeMB \r\n  FROM [MonitoringDB].[dbo].[META2_M_InstanceInfo]  A\r\n INNER JOIN [MonitoringDB].[dbo].[TB_DataSizeGrowth_S] B \r\n    ON A.InstanceID = B.instanceID\r\n INNER JOIN (\r\n\t\t\tSELECT T1.InstanceID\r\n\t\t\t      ,T1.databaseName\r\n\t\t\t  FROM [TBL2_M_DatabaseDiskUsage] T1\r\n\t\t\t      ,(\r\n\t\t\t\t      SELECT InstanceID\r\n\t\t\t\t\t\t        ,MAX(CollectDate) AS CollectDate\r\n\t\t\t\t\t    FROM [TBL2_M_DatabaseDiskUsage]\r\n\t\t\t\t\t   WHERE 1=1\r\n\t\t\t\t\t     AND $__timeFilter(CollectDate)\r\n\t\t\t\t\t   GROUP BY InstanceID\r\n\t\t\t\t   ) T2\r\n\t\t\t WHERE T1.InstanceID = T2.InstanceID\r\n\t\t\t   AND T1.CollectDate = T2.CollectDate\r\n\t\t\t GROUP BY T1.InstanceID, T1.databaseName\r\n\t       ) AS dku2\r\n\t  ON dku2.InstanceID = B.InstanceID AND dku2.databaseName = B.databaseName    \r\n WHERE $__timeFilter(B.CollectDate) \r\n   AND B.databaseName NOT IN ('master','tempdb','model','msdb')\r\n   AND A.ServerName IN ($ServerName)\t\t\r\n   AND A.UseYN = 'Y'\t\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "MS-SQL Storage Usage(Log, GB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "rawSql": "\tSELECT B.CollectDate as time,\r\n\t   A.ServerName +'  ' + B.databaseName as databaseName,\r\n\t   B.TotalSizeMB/1024 as TotalSizeMB\r\n\tFROM [MonitoringDB].[dbo].[META2_M_InstanceInfo]  A\r\n\t\tINNER JOIN [MonitoringDB].[dbo].[TB_LogSizeGrowth_S]  B\r\n\t\tON A.InstanceID = B.instanceID\r\n\t\tAND $__timeFilter(B.CollectDate) \r\n\t\tAND B.databaseName NOT IN ('master','tempdb','model','msdb')\r\n\t\tAND a.ServerName IN($ServerName)\r\n\t\tAND A.UseYN = 'Y'\r\n INNER JOIN (\r\n\t\t\tSELECT T1.InstanceID\r\n\t\t\t      ,T1.databaseName\r\n\t\t\t  FROM [TBL2_M_DatabaseDiskUsage] T1\r\n\t\t\t      ,(\r\n\t\t\t\t      SELECT InstanceID\r\n\t\t\t\t\t\t        ,MAX(CollectDate) AS CollectDate\r\n\t\t\t\t\t    FROM [TBL2_M_DatabaseDiskUsage]\r\n\t\t\t\t\t   WHERE 1=1\r\n\t\t\t\t\t     AND $__timeFilter(CollectDate)\r\n\t\t\t\t\t   GROUP BY InstanceID\r\n\t\t\t\t   ) T2\r\n\t\t\t WHERE T1.InstanceID = T2.InstanceID\r\n\t\t\t   AND T1.CollectDate = T2.CollectDate\r\n\t\t\t GROUP BY T1.InstanceID, T1.databaseName\r\n\t       ) AS dku2\r\n\t  ON dku2.InstanceID = B.InstanceID AND dku2.databaseName = B.databaseName\t\t\r\norder by time"
    },
    {
     "rawSql": "\tSELECT B.CollectDate as time,\r\n\t   A.ServerName +'  ' + B.databaseName as databaseName,\r\n\t   B.UsedSizeMB/1024 as UsedSizeMB \r\n\tFROM [MonitoringDB].[dbo].[META2_M_InstanceInfo]  A\r\n\t\tINNER JOIN [MonitoringDB].[dbo].[TB_LogSizeGrowth_S]  B\r\n\t\tON A.InstanceID = B.instanceID\r\n\t\tAND $__timeFilter(B.CollectDate) \r\n\t\tAND B.databaseName NOT IN ('master','tempdb','model','msdb')\r\n\t\tAND a.ServerName IN($ServerName)\r\n\t\tAND A.UseYN = 'Y'\r\n INNER JOIN (\r\n\t\t\tSELECT T1.InstanceID\r\n\t\t\t      ,T1.databaseName\r\n\t\t\t  FROM [TBL2_M_DatabaseDiskUsage] T1\r\n\t\t\t      ,(\r\n\t\t\t\t      SELECT InstanceID\r\n\t\t\t\t\t\t        ,MAX(CollectDate) AS CollectDate\r\n\t\t\t\t\t    FROM [TBL2_M_DatabaseDiskUsage]\r\n\t\t\t\t\t   WHERE 1=1\r\n\t\t\t\t\t     AND $__timeFilter(CollectDate)\r\n\t\t\t\t\t   GROUP BY InstanceID\r\n\t\t\t\t   ) T2\r\n\t\t\t WHERE T1.InstanceID = T2.InstanceID\r\n\t\t\t   AND T1.CollectDate = T2.CollectDate\r\n\t\t\t GROUP BY T1.InstanceID, T1.databaseName\r\n\t       ) AS dku2\r\n\t  ON dku2.InstanceID = B.InstanceID AND dku2.databaseName = B.databaseName\t\t\r\norder by time"
    }
   ]
  }
 ]
}