{
 "title": "cms monitoring",
 "description": "Visualize AWS RDS metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "dbinstanceidentifier",
    "label": "DBInstanceIdentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "cms CPU Issue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "ldps-prd-cms-mysql" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "cpu",
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "cms Memory Issue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ldps-prd-cms-mysql" },
     "id": "mem",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "cms Strorage Issue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ldps-prd-cms-mysql" },
     "id": "storage",
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  }
 ]
}