{
 "title": "daily check",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "daily check netbackup",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\tT1.ServiceName\r\n\t\t,T1.Schedule\r\n\t\t,T1.Client\r\n\t\t,T1.Policy\r\n\t\t,T1.Started\r\n\t\t,T1.Ended\r\n\t\t,CASE WHEN T1.Ended IS NOT NULL THEN T1.ElapsedTime\r\n\t\t      WHEN T1.Ended IS NULL THEN NULL\r\n\t\t\t  ELSE NULL\r\n\t\t END AS Elapsed\r\n\t\t,FORMAT(100 - (T1.Elapsed / T1.ElpasedStd * 100), '##0.#') + '%' AS ElapsedPerStd\t\t\r\n\t\t,CASE WHEN T1.Status = 0 THEN '정상'\r\n\t\t\t  WHEN T1.STATUS IS NULL AND T1.Ended IS NULL THEN '진행중'\r\n\t\t\t  ELSE '오류'\r\n\t\t END AS Status\r\nFROM\t(\r\n\t\tSELECT CASE WHEN policy = 'lpscsdb01_mssql' THEN '[POS]매출'\r\n\t\t\t\t\tWHEN policy = 'lpgms-sqldb_mssql_lpgms' THEN '[마케팅]사은'\r\n\t\t\t\t\tWHEN policy = 'lpbakdb01_rman_start' THEN '[MD]영업통합'\r\n\t\t\t\t\tWHEN policy = 'lpgcsdb_mssql' THEN '[상품권]상품권'\r\n\t\t\t\t\tWHEN policy = 'culture-sql_mssql' THEN '[마케팅]문화센터'\r\n\t\t\t\t\tWHEN policy = 'ld-hrdb01_rman' THEN '[경영지원]인사'\r\n\t\t\t\t\tWHEN policy = 'dvdb2_rman_start' THEN '[마케팅]배송'\r\n\t\t\t\t\tWHEN policy = 'lpgms-sqldb_mssql_stg' THEN '[마케팅]사은STG'\r\n\t\t\t\t\tWHEN policy = 'lpenr-sqldb_mssql' THEN '[마케팅]에누리'\r\n\t\t\t\t\tWHEN policy = 'ldps_mssql' THEN '[경영지원]동료사원'\r\n\t\t\t\t\tWHEN policy = 'ld-imdb1_mssql' THEN '[경영지원]계정관리'\r\n\t\t\t\t\tWHEN policy = 'lpea-sqldb_mssql' THEN '[경영지원]전자결재'\r\n\t\t\t\t\tELSE policy\r\n\t\t\t   END ServiceName \r\n\t\t\t , Schedule\r\n\t\t\t , Client\r\n\t\t\t , Policy\r\n\t\t\t , format(Started,'yyyy-MM-dd HH:mm:ss') Started\r\n\t\t\t , format(Ended,'yyyy-MM-dd HH:mm:ss') Ended\r\n\t\t\t , STATE as State\r\n\t\t\t , CASE WHEN policy = 'lpscsdb01_mssql' THEN 10800\t\t\t--[POS]매출\t\t\t3시간\r\n\t\t\t\t\tWHEN policy = 'lpgms-sqldb_mssql_lpgms' THEN 7200\t--[마케팅]사은\t\t3시간\r\n\t\t\t\t\tWHEN policy = 'lpbakdb01_rman_start' THEN 43200\t\t--[MD]영업통합\t\t12시간\r\n\t\t\t\t\tWHEN policy = 'lpgcsdb_mssql' THEN 10800\t\t\t--[상품권]상품권\t2시간\r\n\t\t\t\t\tWHEN policy = 'culture-sql_mssql' THEN 1800\t\t\t--[마케팅]문화센터\t30분\r\n\t\t\t\t\tWHEN policy = 'ld-hrdb01_rman' THEN 3600\t\t\t--[경지]인사\t\t1시간\r\n\t\t\t\t\tWHEN policy = 'dvdb2_rman_start' THEN 2400\t\t\t--[마케팅]배송\t\t40분\r\n\t\t\t\t\tWHEN policy = 'lpgms-sqldb_mssql_stg' THEN 1500\t\t--[마케팅]사은STG\t25분\r\n\t\t\t\t\tWHEN policy = 'lpenr-sqldb_mssql' THEN 1500\t\t\t--[마케팅]에누리\t25분\r\n\t\t\t\t\tWHEN policy = 'ldps_mssql' THEN 720\t\t\t\t\t--[경지]동료사원\t12분\r\n\t\t\t\t\tWHEN policy = 'ld-imdb1_mssql' THEN 2400\t\t\t--[경지]계정관리\t40분\r\n\t\t\t\t\tWHEN policy = 'lpea-sqldb_mssql' THEN 3900\t\t\t--[경지]전자결재\t1시간5분\r\n\t\t\t\t\tELSE policy\r\n\t\t\t   END ElpasedStd\r\n\t\t\t , CASE WHEN Ended IS NOT NULL THEN Elapsed ELSE NULL END AS Elapsed\r\n\t\t\t , format(ENDED - STARTED,'HH:mm:ss') AS ElapsedTime\r\n\t\t\t , Status\r\n\t\t  FROM TB_Bak_Stat_Chk_L\r\n\t\t WHERE 1=1\r\n\t\t   AND collectDT = convert(varchar(8),getdate(),112)\r\n\t\t   AND policy in ('lpscsdb01_mssql',\r\n\t\t\t\t\t\t  'lpgms-sqldb_mssql_lpgms',\r\n\t\t\t\t\t\t  'lpbakdb01_rman_start',\r\n\t\t\t\t\t\t  'lpgcsdb_mssql',\r\n\t\t\t\t\t\t  'culture-sql_mssql',\r\n\t\t\t\t\t\t  'ld-hrdb01_rman',\r\n\t\t\t\t\t\t  'dvdb2_rman_start',\r\n\t\t\t\t\t\t  'lpgms-sqldb_mssql_stg',\r\n\t\t\t\t\t\t  'lpenr-sqldb_mssql',\r\n\t\t\t\t\t\t  'ldps_mssql',\r\n\t\t\t\t\t\t  'ld-imdb1_mssql',\r\n\t\t\t\t\t\t  'lpea-sqldb_mssql')\r\n\t\t   AND Schedule = 'full_daily'\r\n\t\t) T1",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "daily check rds",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT VPC, CASE WHEN VPC = 'DEV' THEN 0\r\n                 WHEN VPC = 'SOL' THEN 1\r\n                 WHEN VPC = 'PRD' THEN 2\r\n             END AS GBN\r\n     , r.ServerHost, ServerName\r\n     , VPC_Zone as ZONE--, SUBSTRING(VPC_Zone,LEN(VPC_Zone),1) as ZONE\r\n     , ServerClass, ISNULL(e.ERR_CNT,0) as ERR_CNT\r\n     /*, DBMS_Version, Log_List, Status */\r\n     , Memory_GB as MEM_GB, Storage_Size_GB as Storage_GB, Storage_Type, iops\r\n     , CPUUtilization as CPU_PCT\r\n     , ROUND((1-(FreeableMemory/(Memory_GB*1024*1024*1024)))*100,2) as MEM_PCT\r\n     , ROUND((1-(FreeStorageSpace/(CAST(Storage_Size_GB as BIGINT)*1024*1024*1024)))*100, 2) as Storage_PCT\r\n     , TotalIOPS\r\n     , CollectDT, CollectHH, CollectDTM\r\n  FROM (\r\n        SELECT a.VPC, a.ServerHost, a.ServerName, a.VPC_Zone, a.ServerClass/*, a.DBMS_Version, a.Log_List, a.Status*/\r\n             , a.Storage_Size_GB, b.Memory_GB, a.Storage_Type, a.iops, c.CPUUtilization, c.FreeableMemory, c.FreeStorageSpace, c.ReadIOPS, c.WriteIOPS, c.ReadIOPS + c.WriteIOPS as TotalIOPS\r\n             , c.CollectDT, c.CollectHH, c.CollectDTM\r\n             , RANK() OVER( PARTITION BY a.ServerHost ORDER BY c.CollectDT DESC, c.CollectHH DESC, c.CollectDTM DESC) RNK\r\n        FROM [dbo].[TB_Rds_Comm_Info_M] A\r\n\t        inner join [dbo].[TB_Rds_Class_Info_M] B\r\n            on A.ServerClass = B.ServerClass\r\n\t        left join (SELECT ServerHost\r\n\t\t\t         , CollectDT\r\n\t\t\t         , CollectHH\r\n\t\t\t         , MAX(CollectDTM) AS CollectDTM\r\n                     , MAX([CPUUtilization]) AS [CPUUtilization]\r\n\t\t\t         , MIN([FreeableMemory]) AS [FreeableMemory]\r\n\t\t\t         , MIN([FreeStorageSpace]) AS [FreeStorageSpace]\r\n\t\t\t         , MAX([ReadIOPS]) AS [ReadIOPS]\r\n\t\t\t         , MAX([WriteIOPS]) AS [WriteIOPS]\r\n\t\t        FROM (SELECT ServerHost\r\n\t\t\t\t           , CollectDT\r\n\t\t\t\t           , CollectHH\r\n\t\t\t\t           , CollectDTM\r\n\t\t\t\t           , Rsrc_Name\r\n\t\t\t\t           , Rsrc_Val\r\n\t\t\t           FROM [dbo].[TB_Rds_Rsrc_L] Z\r\n\t\t\t          WHERE Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n\t\t\t        ) AS x\r\n\t\t        Pivot(Max(Rsrc_Val) FOR Rsrc_Name IN ([CPUUtilization], [FreeableMemory], [FreeStorageSpace], [ReadIOPS], [WriteIOPS])) AS pv\r\n\t\t        GROUP BY ServerHost, CollectDT, CollectHH\r\n\t\t        ) AS C on A.ServerHost = C.ServerHost\r\n       ) AS R\r\n       left join (SELECT d.ServerHost, COUNT(d.CollectDT) ERR_CNT\r\n                    FROM [dbo].[TB_RDS_ERR_CHK_L] D\r\n                   WHERE D.CollectDT BETWEEN CONVERT(VARCHAR, GETDATE()-1, 112) AND CONVERT(VARCHAR, GETDATE(), 112) \r\n                  GROUP BY d.ServerHost) E on r.ServerHost = e.ServerHost\r\n WHERE RNK = 1\t\r\n ORDER BY VPC DESC, r.ServerHost",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "daily check RDS maintenance ",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT CollectDTM, \n       SUBSTRING(ResourceIdentifier,CHARINDEX(':db:',(ResourceIdentifier))+LEN(':db:'),LEN(ResourceIdentifier)) as Target, \n       Summary, Detail, AutoAppliedAfterDate as AutoApp, ForcedApplyDate as ForceApp, CurrentApplyDate as CurApp\nFROM dbo.TB_Rds_Maintenance_L\nwhere CollectDTM >= GETDATE()-1\norder by CollectDTM desc"
    }
   ]
  },
  {
   "title": "daily check dms",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT Inst_Name, Identifier_Name, Table_name\r\n     , IncomingChanges, ChangesDiskTarget\r\n     , ThroughputRowsSource, ThroughputRowsTarget\r\n     , LatencySource, LatencyTarget\r\n     , CollectDT, CollectHH, CollectDTM\r\n  FROM (\r\n        SELECT a.Inst_Name, a.Identifier_Name, a.Table_name\r\n             , c.CollectDT, c.CollectHH, c.CollectDTM\r\n             , c.IncomingChanges, c.ChangesDiskTarget\r\n             , c.ThroughputRowsSource, c.ThroughputRowsTarget\r\n             , c.LatencySource, c.LatencyTarget\r\n             , RANK() OVER( PARTITION BY a.Inst_Name, a.Task_Name ORDER BY c.CollectDT DESC, c.CollectHH DESC, c.CollectDTM DESC) RNK\r\n          FROM [dbo].[TB_Dms_Comm_Info_M] A\r\n            INNER join (\r\n                       SELECT Inst_Name, Task_Name\r\n                            , CollectDT\r\n                            , CollectHH\r\n                            , MAX(CollectDTM)                AS CollectDTM\r\n                            , MAX([CDCIncomingChanges])      AS [IncomingChanges]\r\n                            , MAX([CDCChangesDiskTarget])    AS [ChangesDiskTarget]\r\n                            , MAX([CDCThroughputRowsSource]) AS [ThroughputRowsSource]\r\n                            , MAX([CDCThroughputRowsTarget]) AS [ThroughputRowsTarget]\r\n                            , MAX([CDCLatencySource])        AS [LatencySource]\r\n                            , MAX([CDCLatencyTarget])        AS [LatencyTarget]\r\n                    FROM (SELECT Inst_Name\r\n                               , Task_Name\r\n                               , CollectDT\r\n                               , CollectHH\r\n                               , CollectDTM\r\n                               , Rsrc_Name\r\n                               , Rsrc_Val \r\n                           FROM (SELECT Inst_Name\r\n                                      , Task_Name\r\n                                      , CollectDT\r\n                                      , CollectHH\r\n                                      , CollectDTM\r\n                                      , Rsrc_Name\r\n                                      , Rsrc_Val\r\n                                      , RANK() OVER(PARTITION BY Inst_Name, Task_Name order by CollectDTM desc)  RNK\r\n                                  FROM [dbo].[TB_Dms_Rsrc_L] Z\r\n                                 WHERE Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n                                  -- AND Z.CollectHH = \r\n                                  ) Z\r\n                           WHERE RNK = 1\r\n                        ) AS x\r\n                    Pivot(MAX(Rsrc_Val) FOR Rsrc_Name IN ([CDCIncomingChanges], [CDCChangesDiskTarget], [CDCThroughputRowsSource], [CDCThroughputRowsTarget], [CDCLatencySource], [CDCLatencyTarget])) AS pv\r\n                    GROUP BY Inst_Name, Task_Name, CollectDT, CollectHH\r\n                ) AS C\r\n         on A.Inst_Name = C.Inst_Name\r\n        and A.Task_Name = C.Task_Name\r\n  ) AS E\r\n WHERE RNK = 1\t\r\n ORDER BY table_name",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}