{
 "title": "daily check detail DMS",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "metricName": "CPUUtilization", "namespace": "AWS/DMS", "region": "ap-northeast-2", "statistics": [ "Maximum" ] }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "*"
     },
     "metricName": "ReadIOPS",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    },
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "*"
     },
     "metricName": "WriteIOPS",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Storage/Mem Free(GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "metricName": "FreeableMemory", "namespace": "AWS/DMS", "region": "ap-northeast-2", "statistics": [ "Minimum" ] },
    { "metricName": "FreeStorageSpace", "namespace": "AWS/RDS", "region": "ap-northeast-2", "statistics": [ "Minimum" ] }
   ]
  },
  {
   "title": "IO Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "*"
     },
     "metricName": "ReadLatency",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    },
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "*"
     },
     "metricName": "WriteLatency",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "IncomingChanges",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "ldps-prd-rts-dms",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCIncomingChanges",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ChangesDiskTarget",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "ldps-prd-rts-dms",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCChangesDiskTarget",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ThroughputRowsSource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "ldps-prd-rts-dms",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCThroughputRowsSource",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ThroughputRowsTarget",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "ldps-prd-rts-dms",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCThroughputRowsTarget",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "LatencySource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "ldps-prd-rts-dms",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCLatencySource",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "LatencyTarget",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ReplicationInstanceIdentifier": "ldps-prd-rts-dms",
      "ReplicationTaskIdentifier": "*"
     },
     "metricName": "CDCLatencyTarget",
     "namespace": "AWS/DMS",
     "region": "ap-northeast-2",
     "statistics": [ "Maximum" ]
    }
   ]
  }
 ]
}