{
 "title": "old monthly check RDS resource (HH)",
 "time": { "from": "2022-01-01T00:00:00.000Z", "to": "2022-01-01T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "VPC",
    "query": "select distinct vpc from [dbo].[TB_Rds_Comm_Info_M] "
   },
   {
    "name": "ServerHost",
    "query": "select ServerHost from [dbo].[TB_Rds_Comm_Info_M] "
   }
  ]
 },
 "panels": [
  {
   "title": "[RDS] CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, SUBSTRING(b.CollectDT, 1, 6) + '01 ' + b.CollectHH + ':00:00') time, a.ServerHost, AVG(CPU_PCT)\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n-- AND b.CollectDT LIKE SUBSTRING(CONVERT(VARCHAR(8), REPLACE($__timeTo(),'-',''), 112),1,6) + '%'\r\nGROUP BY SUBSTRING(b.CollectDT, 1, 6), b.CollectHH, a.ServerHost\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[RDS] Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, SUBSTRING(b.CollectDT, 1, 6) + '01 ' + b.CollectHH + ':00:00') time, a.ServerHost, AVG(MEM_USED_PCT)\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n-- AND b.CollectDT LIKE SUBSTRING(CONVERT(VARCHAR(8), REPLACE($__timeTo(),'-',''), 112),1,6) + '%'\r\nGROUP BY SUBSTRING(b.CollectDT, 1, 6), b.CollectHH, a.ServerHost\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[RDS] Read IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, SUBSTRING(b.CollectDT, 1, 6) + '01 ' + b.CollectHH + ':00:00') time, a.ServerHost, AVG(READ_IOPS)\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n-- AND b.CollectDT LIKE SUBSTRING(CONVERT(VARCHAR(8), REPLACE($__timeTo(),'-',''), 112),1,6) + '%'\r\nGROUP BY SUBSTRING(b.CollectDT, 1, 6), b.CollectHH, a.ServerHost\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[RDS] Write IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, SUBSTRING(b.CollectDT, 1, 6) + '01 ' + b.CollectHH + ':00:00') time, a.ServerHost, AVG(WRITE_IOPS)\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n-- AND b.CollectDT LIKE SUBSTRING(CONVERT(VARCHAR(8), REPLACE($__timeTo(),'-',''), 112),1,6) + '%'\r\nGROUP BY SUBSTRING(b.CollectDT, 1, 6), b.CollectHH, a.ServerHost\r\nORDER BY 1,2"
    }
   ]
  }
 ]
}