{
 "title": "realtime dms",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TableName",
    "query": "SELECT Table_Name FROM  TB_Dms_Comm_Info_M"
   }
  ]
 },
 "panels": [
  {
   "title": "realtime dms incomingchanges resource range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT dateadd(hh, -9, CollectDTM) as time\r\n     , replace(a.Table_Name,'tb_pssl_','') Table_Name\r\n     , Z.Rsrc_Val\r\n  FROM [dbo].[TB_Dms_Rsrc_L] Z, TB_Dms_Comm_Info_M a\r\n WHERE 1=1 \r\n   AND a.Task_Name= z.Task_Name\r\n   AND a.Table_Name IN ($TableName)\r\n   -- AND Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n   AND Rsrc_Name = 'CDCThroughputRowsSource'\r\n  -- AND $__timeFilter(CollectDTM)\r\n  -- AND CollectDTM BETWEEN $__timeFrom() AND $__timeTo()\r\n   AND CollectDTM BETWEEN dateadd(hh, 9, convert(datetime,$__timeFrom())) AND dateadd(hh, 9, convert(datetime,$__timeTo()))\r\nORDER BY time\r\n",
     "region": "default",
     "statistic": "Average",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "realtime dms latencysource resource range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT dateadd(hh, -9, CollectDTM) as time\r\n     , replace(a.Table_Name,'tb_pssl_','') Table_Name\r\n     , Z.Rsrc_Val\r\n  FROM [dbo].[TB_Dms_Rsrc_L] Z, TB_Dms_Comm_Info_M a\r\n WHERE 1=1 \r\n   AND a.Task_Name= z.Task_Name\r\n   AND a.Table_Name IN ($TableName)\r\n   -- AND Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n   AND Rsrc_Name = 'CDCLatencySource'\r\n  -- AND $__timeFilter(CollectDTM)\r\n  -- AND CollectDTM BETWEEN $__timeFrom() AND $__timeTo()\r\n   AND CollectDTM BETWEEN dateadd(hh, 9, convert(datetime,$__timeFrom())) AND dateadd(hh, 9, convert(datetime,$__timeTo()))\r\nORDER BY time\r\n",
     "region": "default",
     "statistic": "Average",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "realtime dms latencytarget resource range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT dateadd(hh, -9, CollectDTM) as time\r\n     , replace(a.Table_Name,'tb_pssl_','') Table_Name\r\n     , Z.Rsrc_Val\r\n  FROM [dbo].[TB_Dms_Rsrc_L] Z, TB_Dms_Comm_Info_M a\r\n WHERE 1=1 \r\n   AND a.Task_Name= z.Task_Name\r\n   AND a.Table_Name IN ($TableName)\r\n   -- AND Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n   AND Rsrc_Name = 'CDCLatencyTarget'\r\n  -- AND $__timeFilter(CollectDTM)\r\n  -- AND CollectDTM BETWEEN $__timeFrom() AND $__timeTo()\r\n   AND CollectDTM BETWEEN dateadd(hh, 9, convert(datetime,$__timeFrom())) AND dateadd(hh, 9, convert(datetime,$__timeTo()))\r\nORDER BY time\r\n",
     "region": "default",
     "statistic": "Average",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "realtime dms throughputrowssource resource range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT dateadd(hh, -9, CollectDTM) as time\r\n     , replace(a.Table_Name,'tb_pssl_','') Table_Name\r\n     , Z.Rsrc_Val\r\n  FROM [dbo].[TB_Dms_Rsrc_L] Z, TB_Dms_Comm_Info_M a\r\n WHERE 1=1 \r\n   AND a.Task_Name= z.Task_Name\r\n   AND a.Table_Name IN ($TableName)\r\n   -- AND Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n   AND Rsrc_Name = 'CDCThroughputRowsSource'\r\n  -- AND $__timeFilter(CollectDTM)\r\n  -- AND CollectDTM BETWEEN $__timeFrom() AND $__timeTo()\r\n   AND CollectDTM BETWEEN dateadd(hh, 9, convert(datetime,$__timeFrom())) AND dateadd(hh, 9, convert(datetime,$__timeTo()))\r\nORDER BY time\r\n",
     "region": "default",
     "statistic": "Average",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "realtime dms throughputrowstarget resource range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT dateadd(hh, -9, CollectDTM) as time\r\n     , replace(a.Table_Name,'tb_pssl_','') Table_Name\r\n     , Z.Rsrc_Val\r\n  FROM [dbo].[TB_Dms_Rsrc_L] Z, TB_Dms_Comm_Info_M a\r\n WHERE 1=1 \r\n   AND a.Task_Name= z.Task_Name\r\n   AND a.Table_Name IN ($TableName)\r\n   -- AND Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n   AND Rsrc_Name = 'CDCThroughputRowsTarget'\r\n  -- AND $__timeFilter(CollectDTM)\r\n  -- AND CollectDTM BETWEEN $__timeFrom() AND $__timeTo()\r\n   AND CollectDTM BETWEEN dateadd(hh, 9, convert(datetime,$__timeFrom())) AND dateadd(hh, 9, convert(datetime,$__timeTo()))\r\nORDER BY time\r\n",
     "region": "default",
     "statistic": "Average",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "realtime dms changesdisktarget resource range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT dateadd(hh, -9, CollectDTM) as time\r\n     , replace(a.Table_Name,'tb_pssl_','') Table_Name\r\n     , Z.Rsrc_Val\r\n  FROM [dbo].[TB_Dms_Rsrc_L] Z, TB_Dms_Comm_Info_M a\r\n WHERE 1=1 \r\n   AND a.Task_Name= z.Task_Name\r\n   AND a.Table_Name IN ($TableName)\r\n   -- AND Z.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n   AND Rsrc_Name = 'CDCChangesDiskTarget'\r\n  -- AND $__timeFilter(CollectDTM)\r\n  -- AND CollectDTM BETWEEN $__timeFrom() AND $__timeTo()\r\n   AND CollectDTM BETWEEN dateadd(hh, 9, convert(datetime,$__timeFrom())) AND dateadd(hh, 9, convert(datetime,$__timeTo()))\r\nORDER BY time\r\n",
     "region": "default",
     "statistic": "Average",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}