{
 "title": "resource RDS (3h)",
 "description": "Visualize AWS RDS Resource Usage",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VPC",
    "query": "select distinct vpc from [dbo].[TB_Rds_Comm_Info_M] "
   },
   {
    "name": "ServerHost",
    "query": "select ServerHost from [dbo].[TB_Rds_Comm_Info_M] "
   },
   {
    "name": "Rsrc_Name",
    "query": "'CPUUtilization','FreeStorageSpace','FreeableMemory','ReadIOPS','WriteIOPS'"
   }
  ]
 },
 "panels": [
  {
   "title": "[Choosable] Resource Usage",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "\r\nSELECT time, '[' + $Rsrc_Name + '] ' + ServerHost as ServerHost, \r\n       CASE WHEN $Rsrc_Name = 'CPUUtilization' THEN CPU_PCT\r\n            WHEN $Rsrc_Name = 'FreeStorageSpace' THEN Storage_Used_PCT\r\n            WHEN $Rsrc_Name = 'FreeableMemory' THEN MEM_Used_PCT\r\n            WHEN $Rsrc_Name = 'ReadIOPS' THEN Read_IOPS\r\n            WHEN $Rsrc_Name = 'WriteIOPS' THEN Write_IOPS\r\n            WHEN $Rsrc_Name = 'TotalIOPS' THEN Read_IOPS+Write_IOPS\r\n             END as Usage\r\nFROM (SELECT DATEADD(hh, -9, b.CollectDTM) as time, a.ServerHost\r\n           -- CPU\r\n           , ISNULL(MAX(case when Rsrc_Name = 'CPUUtilization' then Rsrc_Val end),0) CPU_PCT\r\n           -- Storage\r\n           , MIN(a.Storage_Size_GB) as Storage_TOT_GB\r\n           , MIN(CAST(ROUND(case when Rsrc_Name = 'FreeStorageSpace' then Rsrc_Val end /1024/1024/1024,0) as INT)) as Storage_Free_GB\r\n           , MIN(a.Storage_Size_GB) - MIN(CAST(ROUND(case when Rsrc_Name = 'FreeStorageSpace' then Rsrc_Val end/1024/1024/1024,0) as INT)) as Storage_Use_GB\r\n           , CAST((MIN(a.Storage_Size_GB) - MIN(ROUND(case when Rsrc_Name = 'FreeStorageSpace' then Rsrc_Val end/1024/1024/1024,0))) / MIN(a.Storage_Size_GB) * 100 as DECIMAL(10,2)) as Storage_Used_PCT\r\n           -- Memory\r\n           , MIN(c.Memory_GB) as MEM_TOT_GB\r\n           , MIN(CAST(ROUND(case when Rsrc_Name = 'FreeableMemory' then Rsrc_Val end/1024/1024/1024,0) as INT)) as MEM_Free_GB\r\n           , MIN(c.Memory_GB) - MIN(CAST(ROUND(case when Rsrc_Name = 'FreeableMemory' then Rsrc_Val end/1024/1024/1024,0) as INT)) as MEM_Use_GB\r\n           , CAST((MIN(c.Memory_GB) - MIN(ROUND(case when Rsrc_Name = 'FreeableMemory' then Rsrc_Val end/1024/1024/1024,0))) / MIN(c.Memory_GB) * 100 as DECIMAL(10,2)) as MEM_Used_PCT\r\n           -- IOPS\r\n           , MAX(case when Rsrc_Name = 'ReadIOPS' then Rsrc_Val end) as Read_IOPS\r\n           , MAX(case when Rsrc_Name = 'WriteIOPS' then Rsrc_Val end) as Write_IOPS\r\n           , MAX(case when Rsrc_Name = 'ReadIOPS' then Rsrc_Val end) + MAX(case when Rsrc_Name = 'WriteIOPS' then Rsrc_Val end) as TOT_IOPS\r\n        FROM [dbo].[TB_Rds_Comm_Info_M] a with (nolock), [dbo].[TB_Rds_Rsrc_L] b with (nolock), [dbo].[TB_Rds_Class_Info_M] c with (nolock)\r\n       WHERE 1=1\r\n         AND b.CollectDTM BETWEEN DATEADD(hh, 9, $__timeFrom()) AND DATEADD(hh, 9, $__timeTo()) \r\n         AND a.ServerHost  = b.ServerHost\r\n         AND a.ServerClass = c.ServerClass\r\n        -- AND b.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n         AND a.ServerHost IN ($ServerHost)\r\n         AND a.VPC IN ($VPC)\r\n         AND b.Rsrc_Name IN ($Rsrc_Name)\r\n      GROUP BY b.CollectDTM, a.ServerHost\r\n     ) AS ZZ\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "CPUUtilization",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATEADD(hh, -9, CollectDTM) as time, ServerHost, Rsrc_Val\r\n  FROM [dbo].[TB_Rds_Rsrc_L] with (nolock)\r\n WHERE CollectDTM BETWEEN DATEADD(hh, 9, $__timeFrom()) AND DATEADD(hh, 9, $__timeTo()) \r\n   AND Rsrc_Name = 'CPUUtilization'\r\n   AND ServerHost IN ($ServerHost)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "ReadIOPS",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATEADD(hh, -9, CollectDTM) as time, ServerHost, Rsrc_Val\r\n  FROM [dbo].[TB_Rds_Rsrc_L] with (nolock)\r\n WHERE CollectDTM BETWEEN DATEADD(hh, 9, $__timeFrom()) AND DATEADD(hh, 9, $__timeTo()) \r\n   AND Rsrc_Name = 'ReadIOPS'\r\n   AND ServerHost IN ($ServerHost)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "WriteIOPS",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATEADD(hh, -9, CollectDTM) as time, ServerHost, Rsrc_Val\r\n  FROM [dbo].[TB_Rds_Rsrc_L] with (nolock)\r\n WHERE CollectDTM BETWEEN DATEADD(hh, 9, $__timeFrom()) AND DATEADD(hh, 9, $__timeTo()) \r\n   AND Rsrc_Name = 'WriteIOPS'\r\n   AND ServerHost IN ($ServerHost)\r\nORDER BY time"
    }
   ]
  }
 ]
}