{
 "title": "resource RDS (Time)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VPC",
    "query": "select distinct vpc from [dbo].[TB_Rds_Comm_Info_M] "
   },
   {
    "name": "ServerHost",
    "query": "select ServerHost from [dbo].[TB_Rds_Comm_Info_M] "
   }
  ]
 },
 "panels": [
  {
   "title": "[RDS] CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, b.CollectDT + ' ' + b.CollectHH + ':00:00') as time, a.ServerHost, b.CPU_PCT\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[RDS] Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, b.CollectDT + ' ' + b.CollectHH + ':00:00') as time, a.ServerHost, b.MEM_used_PCT\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[RDS] Read IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, b.CollectDT + ' ' + b.CollectHH + ':00:00') as time, a.ServerHost, b.Read_IOPS\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[RDS] Write IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, b.CollectDT + ' ' + b.CollectHH + ':00:00') as time, a.ServerHost, b.Write_IOPS\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[RDS] Total IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select CONVERT(DATETIME, b.CollectDT + ' ' + b.CollectHH + ':00:00') as time, a.ServerHost, b.Read_IOPS + b.Write_IOPS as Total_IOPS\r\nfrom dbo.TB_Rds_Comm_Info_M a with (nolock), dbo.TB_Rds_Monthly_Report_L b with (nolock) \r\nwhere 1=1\r\nAND a.ServerHost = b.ServerHost\r\nAND a.VPC IN ($VPC)\r\nAND a.ServerHost IN ($ServerHost)\r\nAND b.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\nORDER BY 1,2"
    }
   ]
  }
 ]
}