{
 "title": "work check_new",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "PartNm",
    "query": "SELECT TITLE AS PART_NM \n  FROM  DPT D \nWHERE TITLE <> '관리자'\nORDER BY CASE WHEN TITLE = 'MD'       THEN 1\n              WHEN TITLE = '마케팅'   THEN 2\n              WHEN TITLE = '경영지원' THEN 3\n              WHEN TITLE = '재무'     THEN 4\n              WHEN TITLE = 'POS'      THEN 5\n              WHEN TITLE = '상품권'   THEN 6\n              WHEN TITLE = '인프라'   THEN 7\n              ELSE 99 -- 매니저\n          END "
   },
   {
    "name": "MemNm",
    "query": "SELECT M.MEMBERNM\n  FROM MEMBER M\n INNER JOIN DPT D\n    ON M.DPTNO = D.ID\n WHERE M.USEYN = 1\n    AND D.TITLE in($PartNm)\n ORDER BY CASE WHEN D.TITLE = 'MD'       THEN 1\n               WHEN D.TITLE = '마케팅'   THEN 2\n               WHEN D.TITLE = '경영지원' THEN 3\n               WHEN D.TITLE = '재무'     THEN 4\n               WHEN D.TITLE = 'POS'      THEN 5\n               WHEN D.TITLE = '상품권'   THEN 6\n               WHEN D.TITLE = '인프라'   THEN 7\n               ELSE 99 -- 매니저\n           END "
   },
   { "name": "IndivisualNm" }
  ]
 },
 "panels": [
  {
   "title": "work Indivisual",
   "type": "marcusolsson-calendar-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(S.STARTDATE,'%Y-%m-%d %H:%i:%s') AS WORK_ST_DT, DATE_FORMAT(ADDDATE(S.ENDDATE,interval -1 day),'%Y-%m-%d %H:%i:%s') AS WORK_END_DT, \r\n                          D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '점검'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '책임당직' THEN '책임당직'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                    ELSE '기타일정'\r\n                END AS WORK_TYPE\r\n             , concat(S.CONTENT, ' ', S.CONTENT2) as Detail\r\n          FROM MEMBER M\r\n    INNER JOIN DPT D\r\n            ON M.DPTNO = D.ID\r\n    LEFT OUTER JOIN SCHEDULE S\r\n            ON M.ID = S.MEMBERID\r\n          AND S.STARTDATE between CONCAT(SUBSTRING($__timeFrom(),1,8), '01') and CONCAT(SUBSTRING(ADDDATE($__timeFrom(), INTERVAL +1 MONTH),1,8), '01')\r\n    LEFT OUTER JOIN DUTY W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n          -- AND D.TITLE in('MD','마케팅','경영지원','재무','POS','상품권','인프라','영업1담당','영업2담당','지원1담당','지원2담당')\r\n           AND M.MEMBERNM = '$IndivisualNm'\r\n -- ORDER BY S.STARTDATE DESC\r\n "
    }
   ]
  },
  {
   "title": "Working Sheet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "work part",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "        SELECT D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             -- , IFNULL(W.TITLE,'정상출근') AS WORK_TYPE\r\n             -- , CASE WHEN W.TITLE IS NULL                             THEN '정상근무' \r\n             --       WHEN W.TITLE = '점검'                            THEN '정상근무'\r\n             --       WHEN W.TITLE = '근무' AND S.CONTENT = '재택근무' THEN '재택근무'\r\n             --       WHEN W.TITLE = '교육 및 세미나'                  THEN '교육'\r\n             --       WHEN W.TITLE IN ('외근','출장')                  THEN '외근'\r\n             --       WHEN W.TITLE IN ('휴가','휴무(연차/대휴)')       THEN '휴가'\r\n             --       ELSE '기타일정'\r\n             --   END AS WORK_TYPE\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '정상근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                    ELSE '기타일정'\r\n                END AS WORK_TYPE\r\n             , concat(S.CONTENT, ' ', S.CONTENT2) as Detail\r\n          FROM MEMBER M\r\n    INNER JOIN DPT D\r\n            ON M.DPTNO = D.ID\r\n    LEFT OUTER JOIN SCHEDULE S\r\n            ON M.ID = S.MEMBERID\r\n           AND NOW() BETWEEN CONCAT(S.STARTDATE, ' 00:00:00.0') AND CONCAT(S.ENDDATE, ' 00:00:00.0')\r\n    LEFT OUTER JOIN DUTY W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n           AND D.TITLE in($PartNm)\r\n           AND M.MEMBERNM in($MemNm)\r\n ORDER BY CASE WHEN D.TITLE = 'MD'       THEN 1\r\n               WHEN D.TITLE = '마케팅'   THEN 2\r\n               WHEN D.TITLE = '경영지원' THEN 3\r\n               WHEN D.TITLE = '재무'     THEN 4\r\n               WHEN D.TITLE = 'POS'      THEN 5\r\n               WHEN D.TITLE = '상품권'   THEN 6\r\n               WHEN D.TITLE = '인프라'   THEN 7\r\n               ELSE 99 -- 매니저\r\n           END\r\n          , M.MEMBERID"
    }
   ]
  },
  {
   "title": "work",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "\r\nSELECT RESULT.PART_NM\r\n     , SUM(CASE WHEN WORK_TYPE = '정상근무' THEN 1 ELSE 0 END) AS '정상근무'\r\n     , SUM(CASE WHEN WORK_TYPE = '재택근무' THEN 1 ELSE 0 END) AS '재택근무'\r\n     , SUM(CASE WHEN WORK_TYPE = '교육'    THEN 1 ELSE 0 END) AS '교육'   \r\n     , SUM(CASE WHEN WORK_TYPE = '외근'    THEN 1 ELSE 0 END) AS '외근'   \r\n     , SUM(CASE WHEN WORK_TYPE = '휴가'    THEN 1 ELSE 0 END) AS '휴가'   \r\n     , SUM(CASE WHEN WORK_TYPE = '기타일정' THEN 1 ELSE 0 END) AS '기타일정'\r\n  FROM (SELECT D.TITLE AS PART_NM, M.MEMBERNM AS MEM_NM\r\n             -- , IFNULL(W.TITLE,'정상출근') AS WORK_TYPE--, S.CONTENT, S.CONTENT2\r\n             -- , CASE WHEN W.TITLE IS NULL                             THEN '정상근무' \r\n             --       WHEN W.TITLE = '점검'                            THEN '정상근무'\r\n             --       WHEN W.TITLE = '근무' AND S.CONTENT = '재택근무' THEN '재택근무'\r\n             --       WHEN W.TITLE = '교육 및 세미나'                  THEN '교육'\r\n             --       WHEN W.TITLE IN ('외근','출장')                  THEN '외근'\r\n             --       WHEN W.TITLE IN ('휴가','휴무(연차/대휴)')       THEN '휴가'\r\n             --       ELSE '기타일정'\r\n             --   END AS WORK_TYPE\r\n             , CASE WHEN W.ID IS NULL                        THEN '정상근무' \r\n                    WHEN W.ID = 6                            THEN '정상근무'\r\n                    WHEN W.ID = 5 AND S.CONTENT = '재택근무' THEN '재택근무'\r\n                    WHEN W.ID = 2                            THEN '교육'\r\n                    WHEN W.ID IN (4,8)                       THEN '외근'\r\n                    WHEN W.ID IN (1,3)                       THEN '휴가'\r\n                    ELSE '기타일정'\r\n                END AS WORK_TYPE\r\n          FROM MEMBER M\r\n    INNER JOIN DPT D\r\n            ON M.DPTNO = D.ID\r\n    LEFT OUTER JOIN SCHEDULE S\r\n            ON M.ID = S.MEMBERID\r\n           AND NOW() BETWEEN CONCAT(S.STARTDATE, ' 00:00:00.0') AND CONCAT(S.ENDDATE, ' 00:00:00.0')\r\n    LEFT OUTER JOIN DUTY W\r\n            ON S.DUTYID = W.ID\r\n         WHERE M.USEYN = 1\r\n       ) AS RESULT\r\n-- PART CODE는 따로 SELECT 하지 않음\r\nGROUP BY RESULT.PART_NM\r\nORDER BY CASE WHEN PART_NM = 'MD'       THEN 1\r\n              WHEN PART_NM = '마케팅'   THEN 2\r\n              WHEN PART_NM = '경영지원' THEN 3\r\n              WHEN PART_NM = '재무'     THEN 4\r\n              WHEN PART_NM = 'POS'      THEN 5\r\n              WHEN PART_NM = '상품권'   THEN 6\r\n              WHEN PART_NM = '인프라'   THEN 7\r\n              ELSE 99 -- 매니저\r\n          END "
    }
   ]
  }
 ]
}