{
 "title": "daily check",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "daily check mssql",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "EXEC [dbo].[usp_ShowDailyReport] \n/*\n\tSELECT \n\t\t\t[INST_ID],\n\t\t\t[JOB_NM],\n\t\t\t[IP_ADDR],\n\t\t\t[CLU_NODE_NM],\n\t\t\t[CLU_CMPS_YN],\n\t\t\t[AGENT_WRK_FAIL_CNT],\n\t\t\t[ERR_LOG_CNT],\n\t\t\t[MEM_USE_PCT],\n\t\t\t[DRV1],[USE1],\n\t\t\t[DRV2],[USE2],\n\t\t\t[DRV3],[USE3],\n\t\t\t[DRV4],[USE4],\n\t\t\t[DRV5],[USE5],\n\t\t\t[DRV6],[USE6],\n\t\t\t-- [DRV7],[USE7],\n\t\t\t-- [DRV8],[USE8],\n\t\t\t-- [DRV9],[USE9],\n\t\t\t[INP_DTM],\n\t\t\t[CLCT_DTM] \n\tFROM [dbo].[TB_DailyReport_S]\n\tWHERE INP_DTM = (SELECT MAX(INP_DTM) FROM  [dbo].[TB_DailyReport_S]) AND\n\t\t  INST_ID IN (2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 18)\n\tORDER BY INST_ID ASC\n*/"
    }
   ]
  },
  {
   "title": "daily check oracle",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select host_name as ServerName, host_ip, host_name, cpu_usr_pct, cpu_sys_pct, cpu_wio_pct, mem_free_mb, tbs_cnt, err_cnt, dt, hh\r\n  from dba_oracle_daily_report\r\n\r\n-- SELECT CC.HOST_IP, CC.HOST_NAME, AA.CPU_USR_PCT, AA.CPU_SYS_PCT, AA.CPU_WIO_PCT, AA.MEM_FREE_MB, BB.TBS_CNT, DD.ERR_CNT, AA.DT, AA.HH\r\n-- FROM (                                                                                                                                     \r\n--     SELECT CPU.DB_ID, CPU.DT, MAX(CPU.HH) AS HH                                                                                             \r\n--         , MAX(CPU.CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU.CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU.CPU_WIO_PCT) AS CPU_WIO_PCT                    \r\n--         , MIN(MEM.MEM_FREE_MB) AS MEM_FREE_MB                                                                                              \r\n--       FROM (                                                                                                                                \r\n--         SELECT CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                        \r\n--             , MAX(CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU_WIO_PCT) CPU_WIO_PCT                               \r\n--         FROM (                                                                                                                              \r\n--         SELECT C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD') AS DT, TO_CHAR (C.TIME, 'HH24') AS HH,                                                \r\n--                 ROUND(AVG(case when C.OS_ID = 0 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_USR_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 1 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_SYS_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 2 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_WIO_PCT\r\n--           FROM LPSIS1.APM_DB_OS_STAT_10MIN C -- OWNER 변수                                                                    \r\n--           WHERE C.OS_ID in (0,1,2)\r\n--             AND C.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND C.TIME < CURRENT_DATE + 1\r\n--             -- \r\n--             AND C.DB_ID = 7\r\n--             AND C.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'007')::numeric\r\n--             --\r\n--       GROUP BY C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD'), TO_CHAR (C.TIME, 'HH24')                                                             \r\n--         ) AS CPU_USE                                                                                                                        \r\n--         GROUP BY CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                      \r\n--       ) CPU,                                                                                                                               \r\n--       ( SELECT M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD') AS DT, TO_CHAR(M.TIME,'HH24') AS HH,                                                    \r\n--                 MIN(ROUND(M.AVG_VALUE / 1024.0, 1)) AS MEM_FREE_MB                                                                          \r\n--           FROM LPSIS1.APM_DB_OS_STAT_10MIN M -- OWNER 변수                                                                    \r\n--           WHERE M.OS_ID = 4                                                                                                                 \r\n--             AND M.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND M.TIME < CURRENT_DATE + 1\r\n--             --\r\n--             AND M.DB_ID = 7\r\n--             AND M.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'007')::numeric\r\n--             --\r\n--         GROUP BY M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD'), TO_CHAR(M.TIME,'HH24')                                                                \r\n--         ) MEM                                                                                                                               \r\n--     WHERE CPU.DB_ID = MEM.DB_ID                                                                                                            \r\n--       AND CPU.DT    = MEM.DT                                                                                                               \r\n--       AND CPU.HH    = MEM.HH                                                                                                               \r\n--     GROUP BY CPU.DB_ID, CPU.DT                                                                                                              \r\n--     ) AA,                                                                                                                                   \r\n--   (SELECT COUNT(1) AS TBS_CNT\r\n--       FROM ( SELECT A.DB_ID,\r\n--                     TABLESPACE_NAME,  \r\n--                     ROUND((SUM(TOTAL_SPACE) - SUM(FREE_SPACE) )  /1024.0,2) AS USED_SPACE,   \r\n--                     ROUND(SUM(FREE_SPACE)/1024.0,2) AS FREE_SPACE,\r\n--                     ROUND(COALESCE(      \r\n--                     ROUND((SUM(TOTAL_SPACE)/1024.0 - SUM(FREE_SPACE)/1024.0),2) / CASE WHEN ROUND(SUM(TOTAL_SPACE)/1024.0,2) = 0 THEN NULL \r\n--                                                                                       ELSE ROUND(SUM(TOTAL_SPACE)/1024.0,2)\r\n--                                                                                   END, 0) * 100,2) AS USE_PRCT,\r\n--                     DATE_TRUNC('day', A.TIME ) AS TIME\r\n--               FROM LPSIS1.ORA_TABLESPACE_INFO A, (SELECT MAX(TIME) AS MAX_TIME, MAX(PARTITION_KEY) AS PARTITION_KEY, MAX(DB_ID) as DB_ID\r\n--                                                     FROM LPSIS1.ORA_TABLESPACE_INFO\r\n--                                                     WHERE PARTITION_KEY =  concat(to_char(now()- interval '1 day','YYMMDD') ,'007')::int4) B\r\n--               WHERE TIME = B.MAX_TIME\r\n--                 AND A.PARTITION_KEY = B.PARTITION_KEY\r\n--                 --\r\n--                 AND A.DB_ID = B.DB_ID\r\n--                 AND A.TIME >= CURRENT_DATE - 1\r\n--                 AND A.TIME <  CURRENT_DATE + 1\r\n--                 AND A.DB_ID = 7\r\n--                 --\r\n--                 AND TABLESPACE_NAME NOT LIKE '%UNDO%'\r\n--                 AND TABLESPACE_NAME NOT LIKE '%TEMP%'\r\n--             GROUP BY A.DB_ID, TABLESPACE_NAME, DATE_TRUNC('day', A.TIME)\r\n--             ORDER BY USE_PRCT DESC\r\n--   ) TBS_CHK\r\n--       WHERE USE_PRCT > 95) BB                                                                                                              \r\n--     , apm_db_info cc                                                                                                                        \r\n--     , (SELECT COUNT(1) ERR_CNT                                                                                                              \r\n--         FROM LPSIS1.ORA_ALERTLOG_HISTORY Z                                                                                    \r\n--         WHERE TIME >= CURRENT_DATE -1                                                                                                       \r\n--           AND VALUE NOT LIKE '%KILL SESSION%'                                                                                               \r\n--           AND VALUE NOT LIKE '%aborting process unknown ospid%'                                                                      \r\n--           AND VALUE NOT LIKE '%ORA-01013%'                                                                                                  \r\n--           AND VALUE NOT LIKE '%SQL Analyze time limit interrupt%'\r\n--           -- \r\n--           AND PARTITION_KEY in (concat(to_char(now(),'YYMMDD') ,'007')::numeric, concat(to_char(now() - interval '1 day','YYMMDD') ,'007')::numeric)\r\n--           AND DB_ID = 7\r\n--           --\r\n--     ) DD                                                                                                                                   \r\n-- where aa.db_id = cc.db_id\r\n-- UNION ALL\r\n-- SELECT CC.HOST_IP, CC.HOST_NAME, AA.CPU_USR_PCT, AA.CPU_SYS_PCT, AA.CPU_WIO_PCT, AA.MEM_FREE_MB, BB.TBS_CNT, DD.ERR_CNT, AA.DT, AA.HH\r\n-- FROM (                                                                                                                                     \r\n--     SELECT CPU.DB_ID, CPU.DT, MAX(CPU.HH) AS HH                                                                                             \r\n--         , MAX(CPU.CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU.CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU.CPU_WIO_PCT) AS CPU_WIO_PCT                    \r\n--         , MIN(MEM.MEM_FREE_MB) AS MEM_FREE_MB                                                                                              \r\n--       FROM (                                                                                                                                \r\n--         SELECT CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                        \r\n--             , MAX(CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU_WIO_PCT) CPU_WIO_PCT                               \r\n--         FROM (                                                                                                                              \r\n--         SELECT C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD') AS DT, TO_CHAR (C.TIME, 'HH24') AS HH,                                                \r\n--                 ROUND(AVG(case when C.OS_ID = 0 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_USR_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 1 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_SYS_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 2 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_WIO_PCT\r\n--           FROM LPSIS2.APM_DB_OS_STAT_10MIN C -- OWNER 변수                                                                    \r\n--           WHERE C.OS_ID in (0,1,2)\r\n--             AND C.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND C.TIME < CURRENT_DATE + 1\r\n--             -- \r\n--             AND C.DB_ID = 8\r\n--             AND C.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'008')::numeric\r\n--             --\r\n--       GROUP BY C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD'), TO_CHAR (C.TIME, 'HH24')                                                             \r\n--         ) AS CPU_USE                                                                                                                        \r\n--         GROUP BY CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                      \r\n--       ) CPU,                                                                                                                               \r\n--       ( SELECT M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD') AS DT, TO_CHAR(M.TIME,'HH24') AS HH,                                                    \r\n--                 MIN(ROUND(M.AVG_VALUE / 1024.0, 1)) AS MEM_FREE_MB                                                                          \r\n--           FROM LPSIS2.APM_DB_OS_STAT_10MIN M -- OWNER 변수                                                                    \r\n--           WHERE M.OS_ID = 4                                                                                                                 \r\n--             AND M.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND M.TIME < CURRENT_DATE + 1\r\n--             --\r\n--             AND M.DB_ID = 8\r\n--             AND M.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'008')::numeric\r\n--             --\r\n--         GROUP BY M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD'), TO_CHAR(M.TIME,'HH24')                                                                \r\n--         ) MEM                                                                                                                               \r\n--     WHERE CPU.DB_ID = MEM.DB_ID                                                                                                            \r\n--       AND CPU.DT    = MEM.DT                                                                                                               \r\n--       AND CPU.HH    = MEM.HH                                                                                                               \r\n--     GROUP BY CPU.DB_ID, CPU.DT                                                                                                              \r\n--     ) AA,                                                                                                                                   \r\n--   (SELECT COUNT(1) AS TBS_CNT\r\n--       FROM ( SELECT A.DB_ID,\r\n--                     TABLESPACE_NAME,  \r\n--                     ROUND((SUM(TOTAL_SPACE) - SUM(FREE_SPACE) )  /1024.0,2) AS USED_SPACE,   \r\n--                     ROUND(SUM(FREE_SPACE)/1024.0,2) AS FREE_SPACE,\r\n--                     ROUND(COALESCE(      \r\n--                     ROUND((SUM(TOTAL_SPACE)/1024.0 - SUM(FREE_SPACE)/1024.0),2) / CASE WHEN ROUND(SUM(TOTAL_SPACE)/1024.0,2) = 0 THEN NULL \r\n--                                                                                       ELSE ROUND(SUM(TOTAL_SPACE)/1024.0,2)\r\n--                                                                                   END, 0) * 100,2) AS USE_PRCT,\r\n--                     DATE_TRUNC('day', A.TIME ) AS TIME\r\n--               FROM LPSIS2.ORA_TABLESPACE_INFO A, (SELECT MAX(TIME) AS MAX_TIME, MAX(PARTITION_KEY) AS PARTITION_KEY, MAX(DB_ID) as DB_ID\r\n--                                                     FROM LPSIS2.ORA_TABLESPACE_INFO\r\n--                                                     WHERE PARTITION_KEY =  concat(to_char(now()- interval '1 day','YYMMDD') ,'008')::int4) B\r\n--               WHERE TIME = B.MAX_TIME\r\n--                 AND A.PARTITION_KEY = B.PARTITION_KEY\r\n--                 --\r\n--                 AND A.DB_ID = B.DB_ID\r\n--                 AND A.TIME >= CURRENT_DATE - 1\r\n--                 AND A.TIME <  CURRENT_DATE + 1\r\n--                 AND A.DB_ID = 8\r\n--                 --\r\n--                 AND TABLESPACE_NAME NOT LIKE '%UNDO%'\r\n--                 AND TABLESPACE_NAME NOT LIKE '%TEMP%'\r\n--             GROUP BY A.DB_ID, TABLESPACE_NAME, DATE_TRUNC('day', A.TIME)\r\n--             ORDER BY USE_PRCT DESC\r\n--   ) TBS_CHK\r\n--       WHERE USE_PRCT > 95) BB                                                                                                              \r\n--     , apm_db_info cc                                                                                                                        \r\n--     , (SELECT COUNT(1) ERR_CNT                                                                                                              \r\n--         FROM LPSIS2.ORA_ALERTLOG_HISTORY Z                                                                                    \r\n--         WHERE TIME >= CURRENT_DATE -1                                                                                                       \r\n--           AND VALUE NOT LIKE '%KILL SESSION%'                                                                                               \r\n--           AND VALUE NOT LIKE '%aborting process unknown ospid%'                                                                      \r\n--           AND VALUE NOT LIKE '%ORA-01013%'                                                                                                  \r\n--           AND VALUE NOT LIKE '%SQL Analyze time limit interrupt%'\r\n--           -- \r\n--           AND PARTITION_KEY in (concat(to_char(now(),'YYMMDD') ,'008')::numeric, concat(to_char(now() - interval '1 day','YYMMDD') ,'008')::numeric)\r\n--           AND DB_ID = 8\r\n--           --\r\n--     ) DD                                                                                                                                   \r\n-- where aa.db_id = cc.db_id\r\n-- UNION ALL\r\n-- SELECT CC.HOST_IP, CC.HOST_NAME, AA.CPU_USR_PCT, AA.CPU_SYS_PCT, AA.CPU_WIO_PCT, AA.MEM_FREE_MB, BB.TBS_CNT, DD.ERR_CNT, AA.DT, AA.HH\r\n-- FROM (                                                                                                                                     \r\n--     SELECT CPU.DB_ID, CPU.DT, MAX(CPU.HH) AS HH                                                                                             \r\n--         , MAX(CPU.CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU.CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU.CPU_WIO_PCT) AS CPU_WIO_PCT                    \r\n--         , MIN(MEM.MEM_FREE_MB) AS MEM_FREE_MB                                                                                              \r\n--       FROM (                                                                                                                                \r\n--         SELECT CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                        \r\n--             , MAX(CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU_WIO_PCT) CPU_WIO_PCT                               \r\n--         FROM (                                                                                                                              \r\n--         SELECT C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD') AS DT, TO_CHAR (C.TIME, 'HH24') AS HH,                                                \r\n--                 ROUND(AVG(case when C.OS_ID = 0 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_USR_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 1 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_SYS_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 2 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_WIO_PCT\r\n--           FROM LOTTEHRS1.APM_DB_OS_STAT_10MIN C -- OWNER 변수                                                                    \r\n--           WHERE C.OS_ID in (0,1,2)\r\n--             AND C.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND C.TIME < CURRENT_DATE + 1\r\n--             -- \r\n--             AND C.DB_ID = 5\r\n--             AND C.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'005')::numeric\r\n--             --\r\n--       GROUP BY C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD'), TO_CHAR (C.TIME, 'HH24')                                                             \r\n--         ) AS CPU_USE                                                                                                                        \r\n--         GROUP BY CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                      \r\n--       ) CPU,                                                                                                                               \r\n--       ( SELECT M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD') AS DT, TO_CHAR(M.TIME,'HH24') AS HH,                                                    \r\n--                 MIN(ROUND(M.AVG_VALUE / 1024.0, 1)) AS MEM_FREE_MB                                                                          \r\n--           FROM LOTTEHRS1.APM_DB_OS_STAT_10MIN M -- OWNER 변수                                                                    \r\n--           WHERE M.OS_ID = 4                                                                                                                 \r\n--             AND M.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND M.TIME < CURRENT_DATE + 1\r\n--             --\r\n--             AND M.DB_ID = 5\r\n--             AND M.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'005')::numeric\r\n--             --\r\n--         GROUP BY M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD'), TO_CHAR(M.TIME,'HH24')                                                                \r\n--         ) MEM                                                                                                                               \r\n--     WHERE CPU.DB_ID = MEM.DB_ID                                                                                                            \r\n--       AND CPU.DT    = MEM.DT                                                                                                               \r\n--       AND CPU.HH    = MEM.HH                                                                                                               \r\n--     GROUP BY CPU.DB_ID, CPU.DT                                                                                                              \r\n--     ) AA,                                                                                                                                   \r\n--   (SELECT COUNT(1) AS TBS_CNT\r\n--       FROM ( SELECT A.DB_ID,\r\n--                     TABLESPACE_NAME,  \r\n--                     ROUND((SUM(TOTAL_SPACE) - SUM(FREE_SPACE) )  /1024.0,2) AS USED_SPACE,   \r\n--                     ROUND(SUM(FREE_SPACE)/1024.0,2) AS FREE_SPACE,\r\n--                     ROUND(COALESCE(      \r\n--                     ROUND((SUM(TOTAL_SPACE)/1024.0 - SUM(FREE_SPACE)/1024.0),2) / CASE WHEN ROUND(SUM(TOTAL_SPACE)/1024.0,2) = 0 THEN NULL \r\n--                                                                                       ELSE ROUND(SUM(TOTAL_SPACE)/1024.0,2)\r\n--                                                                                   END, 0) * 100,2) AS USE_PRCT,\r\n--                     DATE_TRUNC('day', A.TIME ) AS TIME\r\n--               FROM LOTTEHRS1.ORA_TABLESPACE_INFO A, (SELECT MAX(TIME) AS MAX_TIME, MAX(PARTITION_KEY) AS PARTITION_KEY, MAX(DB_ID) as DB_ID\r\n--                                                     FROM LOTTEHRS1.ORA_TABLESPACE_INFO\r\n--                                                     WHERE PARTITION_KEY =  concat(to_char(now()- interval '1 day','YYMMDD') ,'005')::int4) B\r\n--               WHERE TIME = B.MAX_TIME\r\n--                 AND A.PARTITION_KEY = B.PARTITION_KEY\r\n--                 --\r\n--                 AND A.DB_ID = B.DB_ID\r\n--                 AND A.TIME >= CURRENT_DATE - 1\r\n--                 AND A.TIME <  CURRENT_DATE + 1\r\n--                 AND A.DB_ID = 5\r\n--                 --\r\n--                 AND TABLESPACE_NAME NOT LIKE '%UNDO%'\r\n--                 AND TABLESPACE_NAME NOT LIKE '%TEMP%'\r\n--             GROUP BY A.DB_ID, TABLESPACE_NAME, DATE_TRUNC('day', A.TIME)\r\n--             ORDER BY USE_PRCT DESC\r\n--   ) TBS_CHK\r\n--       WHERE USE_PRCT > 95) BB                                                                                                              \r\n--     , apm_db_info cc                                                                                                                        \r\n--     , (SELECT COUNT(1) ERR_CNT                                                                                                              \r\n--         FROM LOTTEHRS1.ORA_ALERTLOG_HISTORY Z                                                                                    \r\n--         WHERE TIME >= CURRENT_DATE -1                                                                                                       \r\n--           AND VALUE NOT LIKE '%KILL SESSION%'                                                                                               \r\n--           AND VALUE NOT LIKE '%aborting process unknown ospid%'                                                                      \r\n--           AND VALUE NOT LIKE '%ORA-01013%'                                                                                                  \r\n--           AND VALUE NOT LIKE '%SQL Analyze time limit interrupt%'\r\n--           -- \r\n--           AND PARTITION_KEY in (concat(to_char(now(),'YYMMDD') ,'005')::numeric, concat(to_char(now() - interval '1 day','YYMMDD') ,'005')::numeric)\r\n--           AND DB_ID = 5\r\n--           --\r\n--     ) DD                                                                                                                                   \r\n-- where aa.db_id = cc.db_id\r\n-- UNION ALL\r\n-- SELECT CC.HOST_IP, CC.HOST_NAME, AA.CPU_USR_PCT, AA.CPU_SYS_PCT, AA.CPU_WIO_PCT, AA.MEM_FREE_MB, BB.TBS_CNT, DD.ERR_CNT, AA.DT, AA.HH\r\n-- FROM (                                                                                                                                     \r\n--     SELECT CPU.DB_ID, CPU.DT, MAX(CPU.HH) AS HH                                                                                             \r\n--         , MAX(CPU.CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU.CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU.CPU_WIO_PCT) AS CPU_WIO_PCT                    \r\n--         , MIN(MEM.MEM_FREE_MB) AS MEM_FREE_MB                                                                                              \r\n--       FROM (                                                                                                                                \r\n--         SELECT CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                        \r\n--             , MAX(CPU_USR_PCT) AS CPU_USR_PCT, MAX(CPU_SYS_PCT) AS CPU_SYS_PCT, MAX(CPU_WIO_PCT) CPU_WIO_PCT                               \r\n--         FROM (                                                                                                                              \r\n--         SELECT C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD') AS DT, TO_CHAR (C.TIME, 'HH24') AS HH,                                                \r\n--                 ROUND(AVG(case when C.OS_ID = 0 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_USR_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 1 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_SYS_PCT,\r\n--                 ROUND(AVG(case when C.OS_ID = 2 then C.AVG_VALUE / 100.0 else NULL end), 2) AS CPU_WIO_PCT\r\n--           FROM LOTTEHRS2.APM_DB_OS_STAT_10MIN C -- OWNER 변수                                                                    \r\n--           WHERE C.OS_ID in (0,1,2)\r\n--             AND C.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND C.TIME < CURRENT_DATE + 1\r\n--             -- \r\n--             AND C.DB_ID = 6\r\n--             AND C.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'006')::numeric\r\n--             --\r\n--       GROUP BY C.DB_ID, TO_CHAR (C.TIME, 'YYYYMMDD'), TO_CHAR (C.TIME, 'HH24')                                                             \r\n--         ) AS CPU_USE                                                                                                                        \r\n--         GROUP BY CPU_USE.DB_ID, CPU_USE.DT, CPU_USE.HH                                                                                      \r\n--       ) CPU,                                                                                                                               \r\n--       ( SELECT M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD') AS DT, TO_CHAR(M.TIME,'HH24') AS HH,                                                    \r\n--                 MIN(ROUND(M.AVG_VALUE / 1024.0, 1)) AS MEM_FREE_MB                                                                          \r\n--           FROM LOTTEHRS2.APM_DB_OS_STAT_10MIN M -- OWNER 변수                                                                    \r\n--           WHERE M.OS_ID = 4                                                                                                                 \r\n--             AND M.TIME >= CURRENT_DATE                                                                                                      \r\n--             AND M.TIME < CURRENT_DATE + 1\r\n--             --\r\n--             AND M.DB_ID = 6\r\n--             AND M.PARTITION_KEY = concat(to_char(now(),'YYMMDD') ,'006')::numeric\r\n--             --\r\n--         GROUP BY M.DB_ID, TO_CHAR(M.TIME,'YYYYMMDD'), TO_CHAR(M.TIME,'HH24')                                                                \r\n--         ) MEM                                                                                                                               \r\n--     WHERE CPU.DB_ID = MEM.DB_ID                                                                                                            \r\n--       AND CPU.DT    = MEM.DT                                                                                                               \r\n--       AND CPU.HH    = MEM.HH                                                                                                               \r\n--     GROUP BY CPU.DB_ID, CPU.DT                                                                                                              \r\n--     ) AA,                                                                                                                                   \r\n--   (SELECT COUNT(1) AS TBS_CNT\r\n--       FROM ( SELECT A.DB_ID,\r\n--                     TABLESPACE_NAME,  \r\n--                     ROUND((SUM(TOTAL_SPACE) - SUM(FREE_SPACE) )  /1024.0,2) AS USED_SPACE,   \r\n--                     ROUND(SUM(FREE_SPACE)/1024.0,2) AS FREE_SPACE,\r\n--                     ROUND(COALESCE(      \r\n--                     ROUND((SUM(TOTAL_SPACE)/1024.0 - SUM(FREE_SPACE)/1024.0),2) / CASE WHEN ROUND(SUM(TOTAL_SPACE)/1024.0,2) = 0 THEN NULL \r\n--                                                                                       ELSE ROUND(SUM(TOTAL_SPACE)/1024.0,2)\r\n--                                                                                   END, 0) * 100,2) AS USE_PRCT,\r\n--                     DATE_TRUNC('day', A.TIME ) AS TIME\r\n--               FROM LOTTEHRS2.ORA_TABLESPACE_INFO A, (SELECT MAX(TIME) AS MAX_TIME, MAX(PARTITION_KEY) AS PARTITION_KEY, MAX(DB_ID) as DB_ID\r\n--                                                     FROM LOTTEHRS2.ORA_TABLESPACE_INFO\r\n--                                                     WHERE PARTITION_KEY =  concat(to_char(now()- interval '1 day','YYMMDD') ,'006')::int4) B\r\n--               WHERE TIME = B.MAX_TIME\r\n--                 AND A.PARTITION_KEY = B.PARTITION_KEY\r\n--                 --\r\n--                 AND A.DB_ID = B.DB_ID\r\n--                 AND A.TIME >= CURRENT_DATE - 1\r\n--                 AND A.TIME <  CURRENT_DATE + 1\r\n--                 AND A.DB_ID = 6\r\n--                 --\r\n--                 AND TABLESPACE_NAME NOT LIKE '%UNDO%'\r\n--                 AND TABLESPACE_NAME NOT LIKE '%TEMP%'\r\n--             GROUP BY A.DB_ID, TABLESPACE_NAME, DATE_TRUNC('day', A.TIME)\r\n--             ORDER BY USE_PRCT DESC\r\n--   ) TBS_CHK\r\n--       WHERE USE_PRCT > 95) BB                                                                                                              \r\n--     , apm_db_info cc                                                                                                                        \r\n--     , (SELECT COUNT(1) ERR_CNT                                                                                                              \r\n--         FROM LOTTEHRS2.ORA_ALERTLOG_HISTORY Z                                                                                    \r\n--         WHERE TIME >= CURRENT_DATE -1                                                                                                       \r\n--           AND VALUE NOT LIKE '%KILL SESSION%'                                                                                               \r\n--           AND VALUE NOT LIKE '%aborting process unknown ospid%'                                                                      \r\n--           AND VALUE NOT LIKE '%ORA-01013%'                                                                                                  \r\n--           AND VALUE NOT LIKE '%SQL Analyze time limit interrupt%'\r\n--           -- \r\n--           AND PARTITION_KEY in (concat(to_char(now(),'YYMMDD') ,'006')::numeric, concat(to_char(now() - interval '1 day','YYMMDD') ,'006')::numeric)\r\n--           AND DB_ID = 6\r\n--           --\r\n--     ) DD                                                                                                                                   \r\n-- where aa.db_id = cc.db_id"
    }
   ]
  },
  {
   "title": "daily check etc oracle tablespace",
   "type": "table",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 26 },
   "targets": [
    {
     "rawSql": "select a.dbName, a.tbs_name, a.tot_gb, a.free_gb, a.use_gb, a.use_pct\n  from [TB_Ora_Tbs_Chk_L] A with (nolock)\n where 1=1\n   and a.CollectDT = convert(varchar, getdate(), 112) \n  -- and a.RGST_DTM = (SELECT MAX(RGST_DTM) FROM  [dbo].[TB_Ora_Tbs_Chk_L]) \n   and use_pct > 70\norder by a.use_pct desc"
    }
   ]
  },
  {
   "title": "daily check etc oracle",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT ServerName\r\n, IPAddr\r\n, hostName\r\n, cpuUse\r\n, prcsCnt\r\n, memUse\r\n, diskChk\r\n, oraTbsChk\r\n, oraErrChk\r\n, CollectDT\r\n, CollectHH\r\nFROM (\r\n\tSELECT \r\n\t\tA.ServerName\r\n\t\t, A.IPAddr\r\n\t\t, A.hostName\r\n\t\t, B.cpuUse\r\n\t\t, B.memUse\r\n\t\t, B.prcsCnt\r\n\t\t, B.diskChk\r\n\t\t, isnull(C.errChk,0) oraErrChk\r\n\t\t, isnull(D.tbsChk,0) oraTbsChk\r\n\t\t, B.CollectDT\r\n\t\t, B.CollectHH\r\n\t\t, ROW_NUMBER() OVER(PARTITION BY B.hostName, B.CollectDT ORDER BY  B.CollectHH DESC) AS RN\r\n\tFROM dbo.TB_Svr_Comm_Info_M A with (nolock)\r\n\tINNER JOIN dbo.TB_Svr_Rsrc_Chk_L B  with (nolock) ON A.hostName = B.hostName\r\n\tLEFT OUTER JOIN (  \r\n\t\tSELECT hostName, IPAddr, COUNT (1) errChk\r\n\t\tFROM dbo.TB_Ora_Alert_Chk_L with (nolock)\r\n\t\tWHERE 1 = 1 AND collectDT >= CONVERT (varchar, getdate()-1, 112)\r\n\t\tGROUP BY hostName, IPAddr\r\n\t) C ON A.hostName = C.hostName\r\n\tLEFT OUTER JOIN (\r\n\t\tSELECT [dbName], COUNT(1) tbsChk\r\n\t\tFROM [MonitoringDB].[dbo].[TB_Ora_Tbs_Chk_L] with (nolock)\r\n\t\tWHERE collectDT = CONVERT (varchar, getdate(), 112)\r\n\t\tAND use_pct > 95\r\n\t\tGROUP BY [dbName]\r\n\t) D ON D.[dbName] = A.NOTE\r\n\tWHERE 1 = 1        \r\n\tAND B.CollectDT = CONVERT (varchar, getdate(), 112)\r\n\tAND A.UseYn = 'Y'\r\n) Z\r\nWHERE RN = 1\r\nORDER BY Z.hostName, Z.CollectHH DESC, Z.CollectDT"
    }
   ]
  },
  {
   "title": "daily check etc sync",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "rawSql": "exec [dbo].[usp_ShowSyncDBChk]" }
   ]
  },
  {
   "title": "daily check etc batch",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "rawSql": "EXEC DBO.usp_ShowArchBatchChk" }
   ]
  },
  {
   "title": "daily check etc dr",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\t(CASE WHEN SDR.collectDT IS NULL THEN 9999 ELSE TC.TARGET_CNT END) - (CASE WHEN SDR.collectDT IS NULL THEN 0 ELSE SDR.SUCC_CNT END) AS GAP\r\n\t, TC.hostName\r\n\t, SDR.collectDT\r\n\t, (CASE WHEN SDR.collectDT IS NULL THEN NULL ELSE TC.TARGET_CNT END) AS TARGET_CNT\r\n\t, SDR.SUCC_CNT\r\n\t, SDR.SUS_CNT\r\n\t, SDR.RGST_DTM\r\nFROM (\r\n\tSELECT\r\n\t\tROW_NUMBER()OVER(PARTITION BY hostName, CollectDT ORDER BY RGST_DTM DESC) ROWNUM\r\n\t\t, hostName\r\n\t\t, collectDT\r\n\t\t, RGST_DTM\t    \r\n\t    , COUNT(CASE WHEN MESSAGE_TEXT LIKE '%Consistent%' OR MESSAGE_TEXT LIKE '%SyncInProg%' THEN 1\r\n\t\t\t\t\t WHEN MESSAGE_TEXT LIKE '%PAIR%' OR MESSAGE_TEXT LIKE '%COPY%' THEN 1 \r\n\t\t\t\tEND) SUCC_CNT\r\n\t    , COUNT(CASE WHEN MESSAGE_TEXT LIKE '%PSUS%' OR MESSAGE_TEXT LIKE '%SSUS%' OR MESSAGE_TEXT LIKE '%PSUE%' OR MESSAGE_TEXT LIKE '%PFUS%'  THEN 1 \r\n\t\t\t\t\t WHEN MESSAGE_TEXT LIKE '%SUS%'  THEN 1 \r\n\t\t\t    END) SUS_CNT\r\n\tFROM TB_Svr_DR_sync_L with (nolock)\r\n\tWHERE collectDT = CONVERT(VARCHAR(8), getdate(), 112)\r\n\tAND (\r\n\t\t--HITACHI\r\n\t\t   MESSAGE_TEXT LIKE '%PAIR%'\t--성공\r\n\t\tOR MESSAGE_TEXT LIKE '%PSUS%'\t--중지\r\n\t\tOR MESSAGE_TEXT LIKE '%SSUS%'\t--중지\r\n\t\tOR MESSAGE_TEXT LIKE '%PSUE%'\t--실패\r\n\t\tOR MESSAGE_TEXT LIKE '%COPY%'\t--복사중\r\n\t\tOR MESSAGE_TEXT LIKE '%PFUS%'\t--저널용량 문제로 인한 실패\r\n\t\t--EMC\r\n\t\tOR MESSAGE_TEXT LIKE '%Consistent%'\t--성공\r\n\t\tOR MESSAGE_TEXT LIKE '%Suspended%'\t--중지\r\n\t\tOR MESSAGE_TEXT LIKE '%SyncInProg%'\t--복사중\r\n\t\tOR MESSAGE_TEXT LIKE '%Split%'\t--중지\r\n\t\t)   \r\n\tAND MESSAGE_TEXT NOT LIKE '%pairvolchk%' -- 인사 최하단\r\n\tAND MESSAGE_TEXT NOT LIKE '%Group%PairVol(L/R)%' -- 인사, 증빙 컬럼명\r\n    AND MESSAGE_TEXT NOT LIKE '%M(ode%of%Operation)%' -- 상품권 모드 설명\r\n    AND MESSAGE_TEXT NOT LIKE '%(M)ode%of%Operation%' -- 영업통합 모드 설명\r\n    AND MESSAGE_TEXT NOT LIKE '%Logical%Sym%' -- 상품권, 영업통합 컬럼명\r\n\tAND MESSAGE_TEXT NOT LIKE '%A(daptive Copy)%' -- 상품권 모드설명\r\n\tAND MESSAGE_TEXT NOT LIKE '%Adaptive%Copy%WP%Mode%' -- 영업통합 모드설명\r\n\tGROUP BY \r\n\t\thostName\r\n\t\t,CollectDT\r\n\t\t,RGST_DTM\r\n) SDR\r\nRIGHT JOIN (\r\n\tSELECT 'JUNJADB' AS hostName ,5 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'LD-EADB2' AS hostName ,7 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'LD-HRDB02' AS hostName ,28 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'LPGCSDB01' AS hostName ,8 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'lpscsdb01' AS hostName ,7 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'lpsisdb01' AS hostName ,176\tAS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'lpbatap01' AS hostName ,7\tAS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'CULDB1' AS hostName ,6 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'ENRDB1' AS hostName ,6 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'GMSDB01' AS hostName ,10 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'lpdlvdb01' AS hostName ,16 AS TARGET_CNT\r\n\tUNION ALL\r\n\tSELECT 'nas_drm' AS hostName ,4 AS TARGET_CNT\r\n) TC ON SDR.hostname = TC.hostname AND SDR.ROWNUM = 1"
    }
   ]
  },
  {
   "title": "daily check etc bcv",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\thostname\r\n\t, collectDT\r\n\t, STR_TIME\r\n\t, SUCC_TIME\r\n\t, MESSAGE_TEXT\r\nFROM (\r\n\tSELECT \r\n\t\thostname\r\n\t\t, collectDT\r\n\t\t, CASE hostName \r\n\t\t\twhen 'lpsisdb01' then format(getdate(),'yyyy-MM-dd') + ' 00:00:00'\r\n\t\t\twhen 'LD-HRDB02' then format(getdate(),'yyyy-MM-dd') + ' 03:00:00'\r\n\t\t\tend as STR_TIME\r\n\t\t, RIGHT(TARGET,4) + '-' + \r\n\t\t\tCASE LEFT(TARGET,3) \r\n\t\t\t\tWHEN 'Jan' then '01'\r\n\t\t\t\tWHEN 'Feb' then '02'\r\n\t\t\t\tWHEN 'Mar' then '03'\r\n\t\t\t\tWHEN 'Apr' then '04'\r\n\t\t\t\tWHEN 'May' then '05'\r\n\t\t\t\tWHEN 'Jun' then '06'\r\n\t\t\t\tWHEN 'Jul' then '07'\r\n\t\t\t\tWHEN 'Aug' then '08'\r\n\t\t\t\tWHEN 'Sep' then '09'\r\n\t\t\t\tWHEN 'Oct' then '10'\r\n\t\t\t\tWHEN 'Nov' then '11'\r\n\t\t\t\tWHEN 'Dec' then '12'\r\n\t\t\t\tELSE LEFT(TARGET,3) \r\n\t\t\tEND + '-' + \r\n\t\t\tSUBSTRING(TARGET, CHARINDEX(' ',TARGET,1)+1,CHARINDEX(' ',TARGET, CHARINDEX(' ',TARGET,1)+1)-CHARINDEX(' ',TARGET,1)-1) + ' ' + \r\n\t\t\tSUBSTRING(TARGET, CHARINDEX(':',TARGET,1)-2,CHARINDEX(':',TARGET,CHARINDEX(':',TARGET,1)+1)+3-CHARINDEX(':',TARGET,1)+2) as SUCC_TIME\r\n\t\t, MESSAGE_TEXT\r\n\tFROM (\r\n\t\tSELECT \r\n\t\t\thostname, collectDT, MESSAGE_TEXT\r\n\t\t\t, RIGHT(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MESSAGE_TEXT, 'Shadow Image script finished: ',''),'+ echo ',''),' : SUCCESS','') ,'KST ',''),'  ',' 0')) ,20) TARGET\r\n\t\tFROM TB_Svr_BCV_Copy_L with (nolock)\r\n\t\t-- WHERE (MESSAGE_TEXT LIKE '%+ echo %SUCCESS%' OR MESSAGE_TEXT LIKE '%Shadow Image script finished%')\r\n\t\tWHERE MESSAGE_TEXT LIKE '%Shadow Image script finished%'\r\n\t\tAND MESSAGE_TEXT NOT LIKE '+ %'\r\n\t\tAND collectDT = convert(varchar, getdate(), 112)\r\n\t) Z\r\n) Z\r\nWHERE ISDATE(SUCC_TIME) = 1\r\nUNION ALL\r\n--상품권 별도 쿼리 작성\r\nSELECT \r\n\tT1.hostName\r\n\t,T1.CollectDT\r\n\t,convert(datetime,T1.STR_TIME) as STR_TIME\r\n\t,convert(datetime,T1.SUCC_TIME) as SUCC_TIME\r\n\t,CASE WHEN T1.MESSAGE_CNT = 2 THEN 'SI BACKUP SUCCESS'\r\n\t    ELSE 'SI BACKUP FAIL'\r\n\tEND AS MESSAGE_TEXT\r\nFROM (\r\n\tSELECT T1.hostname\r\n\t\t    ,T1.collectDT\r\n\t\t    ,MAX(CASE WHEN MESSAGE_TEXT LIKE '%resync%' THEN LEFT(RIGHT(T1.MESSAGE_TEXT, 24),19) ELSE '' END) AS STR_TIME\r\n\t        ,MAX(CASE WHEN MESSAGE_TEXT LIKE '%pairsplit%' THEN LEFT(RIGHT(T1.MESSAGE_TEXT, 24),19) ELSE '' END) AS SUCC_TIME\r\n\t\t\t,COUNT(1) AS MESSAGE_CNT\r\n\tFROM TB_Svr_BCV_Copy_L T1 with (nolock)\r\n\tWHERE 1=1\r\n\tAND collectDT = convert(varchar, getdate(), 112)\r\n\tAND hostName = 'LPGCSDB01'\r\n\tAND MESSAGE_TEXT LIKE '%time%'\r\n\tGROUP BY hostname, collectDT\r\n) T1"
    }
   ]
  },
  {
   "title": "daily check netbackup",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\t\r\n\tT1.Status\r\n\t,T1.Client\r\n\t,T1.Policy\r\n\t,T1.Schedule\t\r\n\t,T1.Started\r\n\t,T1.Ended\r\n\t,CASE WHEN T1.Ended IS NOT NULL THEN T1.ElapsedTime\r\n\t      WHEN T1.Ended IS NULL THEN NULL\r\n\t\t  ELSE NULL\r\n\t END AS Elapsed, convert(decimal,ElapsedSec) as ElapsedSec\r\n\t--  , ElpasedStd \r\n\t , 1 AS Constant_1\r\n\t , 100 AS Constant_2\r\n\t-- ,FORMAT((T1.Elapsed / T1.ElpasedStd * 100) - 100, '##0.#') AS \"ElapsedPerStd\"\r\nFROM\t(\r\n\tSELECT \r\n\t\tROW_NUMBER()OVER(PARTITION BY POLICY, CollectDT ORDER BY JOBID DESC) ROWNUM\r\n\t\t-- , CASE WHEN policy = 'lpscsdb01_mssql' THEN '[POS] 매출'\r\n\t\t-- \t   WHEN policy = 'lpgms-sqldb_mssql_lpgms' THEN '[마케팅] 사은'\r\n\t\t-- \t   WHEN policy = 'lpbakdb01_rman_start' THEN '[MD] 영업통합'\r\n\t\t-- \t   WHEN policy = 'lpgcsdb_mssql' THEN '[상품권] 상품권'\r\n\t\t-- \t   WHEN policy = 'cul-sqldb_mssql' THEN '[마케팅] 문화센터(신)'\r\n\t\t-- \t   WHEN policy = 'ld-hrdb01_rman' THEN '[경영지원] 인사'\r\n\t\t-- \t   WHEN policy = 'lpdlvdb02_rman' THEN '[마케팅] 배송'\r\n\t\t-- \t   WHEN policy = 'lpgms-sqldb_mssql_stg' THEN '[마케팅] 사은STG'\r\n\t\t-- \t   WHEN policy = 'lpenr-sqlclt-t_mssql' THEN '[마케팅] 에누리'\r\n\t\t-- \t   WHEN policy = 'ldps_mssql' THEN '[경영지원] 동료사원'\r\n\t\t-- \t   WHEN policy = 'ld-imdb1_mssql' THEN '[경영지원] 계정관리'\r\n\t\t-- \t   WHEN policy = 'lpea-sqldb_mssql' THEN '[경영지원] 전자결재'\t\t\t\t\t\r\n\t\t-- \t   ELSE policy END ServiceName \r\n\t\t, Schedule\r\n\t\t, Client\r\n\t\t, Policy\r\n\t\t, format(Started,'yyyy-MM-dd HH:mm:ss') Started\r\n\t\t, format(Ended,'yyyy-MM-dd HH:mm:ss') Ended\r\n\t\t, STATE as State\r\n\t\t-- , CASE WHEN policy = 'lpscsdb01_mssql' THEN 10800\t\t\t--[POS] 매출\t\t\t3시간\r\n\t\t-- \t   WHEN policy = 'lpgms-sqldb_mssql_lpgms' THEN 7500\t--[마케팅] 사은\t\t2시간\r\n\t\t-- \t   WHEN policy = 'lpbakdb01_rman_start' THEN 43200\t\t--[MD] 영업통합\t\t12시간\r\n\t\t-- \t   WHEN policy = 'lpgcsdb_mssql' THEN 10800\t\t\t\t--[상품권] 상품권\t2시간\r\n\t\t-- \t   WHEN policy = 'ld-hrdb01_rman' THEN 3600\t\t\t\t--[경지] 인사\t\t1시간\r\n\t\t-- \t   WHEN policy = 'lpdlvdb02_rman_start' THEN 2400\t\t\t--[마케팅] 배송\t\t40분\r\n\t\t-- \t   WHEN policy = 'lpgms-sqldb_mssql_stg' THEN 1500\t\t--[마케팅] 사은STG\t25분\r\n\t\t-- \t   WHEN policy = 'lpenr-sqldb_mssql' THEN 1800\t\t\t--[마케팅] 에누리\t25분\r\n\t\t-- \t   WHEN policy = 'ldps_mssql' THEN 720\t\t\t\t\t--[경지] 동료사원\t12분\r\n\t\t-- \t   WHEN policy = 'ld-imdb1_mssql' THEN 1500\t\t\t\t--[경지] 계정관리\t25분\r\n\t\t-- \t   WHEN policy = 'lpea-sqldb_mssql' THEN 4800\t\t\t--[경지] 전자결재\t1시간5분\r\n\t\t-- \t   WHEN policy = 'cul-sqldb_mssql' THEN 750\t\t\t--[마케팅] 신문화센터 12분30초\r\n\t\t-- \t   ELSE policy END ElpasedStd\r\n\t\t, CASE WHEN Ended IS NOT NULL THEN Elapsed ELSE NULL END AS Elapsed\r\n\t\t, format(ENDED - STARTED,'HH:mm:ss') AS ElapsedTime\r\n\t\t, Status\r\n\t\t, DATEDIFF (SECOND,STARTED, ENDED) as ElapsedSec\r\n\tFROM TB_Bak_Stat_Chk_L with (nolock)\r\n\tWHERE 1=1\r\n\tAND\t\tCOLLECTDT = CONVERT(VARCHAR(8),GETDATE(),112)\r\n\tAND\t\tSCHEDULE = 'full_daily'\r\n\tAND\t\tPOLICY IN ('lpscsdb01_mssql',\r\n\t\t\t\t\t\t\t\t'lpgms-sqldb_mssql_lpgms',\r\n\t\t\t\t\t\t\t\t'lpbakdb01_rman_start',\r\n\t\t\t\t\t\t\t\t'lpgcsdb_mssql',\r\n\t\t\t\t\t\t\t\t'ld-hrdb01_rman',\r\n\t\t\t\t\t\t\t\t'lpdlvdb02_rman',\r\n\t\t\t\t\t\t\t\t'lpgms-sqldb_mssql_stg',\r\n\t\t\t\t\t\t\t\t'lpenr-sqlclt-t_mssql',\r\n\t\t\t\t\t\t\t\t'ldps_mssql',\r\n\t\t\t\t\t\t\t\t'ld-imdb1_mssql',\r\n\t\t\t\t\t\t\t\t'lpea-sqldb_mssql',\r\n\t\t\t\t\t\t\t\t'cul-sqldb_mssql')\r\n) T1\r\nWHERE T1.ROWNUM = 1\r\nORDER BY Started ASC"
    },
    {
     "rawSql": "SELECT SVC_NM as ServiceName, MAX(POL_NM) as Policy, MAX(ELS_TM) as ELS_TM, MAX(MAX_ELS_TM) as MAX_ELS_TM\r\n  FROM TB_BAK_SOLPOL_M\r\n WHERE SOL_CL_CD = 'NET'\r\n   AND POL_NM NOT IN ('ld-hrdb01_rman_start')\r\nGROUP BY SVC_NM"
    }
   ]
  },
  {
   "title": "daily check comvault",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT T2.Status\r\n     , T1.SVC_NM AS ServiceName\r\n     , T1.POL_NM AS Client\r\n     , T2.Policy\r\n     , T2.Schedule\r\n     , T2.Started\r\n     , T2.Ended\r\n     , RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(SECOND, T2.Started, T2.Ended) / 3600, 2), 2) + ':' + RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(SECOND, T2.Started, T2.Ended) / 60, 2), 2) + ':' + RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(SECOND, T2.Started, T2.Ended) % 60, 2), 2) AS Elapsed\t \r\n     , ((T2.ConvertSec * 1.0) / ((CASE WHEN DATEPART(WEEKDAY, T2.Started) = 1 THEN T1.MAX_ELS_TM ELSE T1.ELS_TM END) * 1.0) * 100) - 100 AS ElapsedPerStd\r\n  FROM TB_BAK_SOLPOL_M T1 with (nolock)\r\n  LEFT OUTER JOIN (\r\n    SELECT\r\n\t\tROW_NUMBER()OVER(PARTITION BY T2.Client ORDER BY T2.STARTTIME DESC) Rownum\r\n\t\t, T2.Status \r\n        , T2.TYPE AS Schedule\r\n        , T2.CLIENT AS Client\r\n        , T2.Instance AS Policy\r\n        , T2.STARTTIME AS Started\r\n        , T2.ENDTIME AS Ended\r\n        , CONVERT(CHAR(8), DATEDIFF(SECOND, T2.STARTTIME, T2.ENDTIME)) AS Elapsed\r\n        --Elapsed Per Time 계산\r\n        , DATEDIFF(SECOND, T2.STARTTIME, T2.ENDTIME) AS ConvertSec            \r\n        FROM TB_CV_BAK_Stat_Chk_L T2 with (nolock)\r\n\t\tWHERE T2.CollectDT = CONVERT(VARCHAR, GETDATE(), 112)\r\n\t\tAND T2.Agent = 'SQL Server'\r\n ) T2 ON T1.POL_NM = T2.Client AND T2.Rownum = 1\r\n WHERE T1.BAK_CL_CD = 'COMVAULT'\r\n ORDER BY T2.Started ASC"
    }
   ]
  }
 ]
}