{
 "title": "daily check backup solution",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DisplayType", "query": "PolicyName, ServiceName" },
   {
    "name": "ServiceName",
    "query": "SELECT SVC_NM FROM TB_BAK_SOLPOL_M"
   },
   {
    "name": "PolicyName",
    "query": "SELECT POL_NM\nFROM TB_BAK_SOLPOL_M\nWHERE SVC_NM IN ($ServiceName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Batch Time Line(NetBackup) (🟦 : SAN 🟩 : NET)",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end AS POL_NM\r\n    --, FORMAT(AVG(started), 'HH:mm:ss') \r\n    , min(started) as StartTime\r\n    , max(ended) as EndTime\r\nfrom TB_Bak_Stat_Chk_L a\r\nwhere 1=1\r\nand POLICY IN ('ld-imdb1_mssql','ldps_mssql','ld-hrdb01_rman','ld-hrdb01_rman_start','lpea-sqldb_mssql','cul-sqldb_mssql','lpdlvdb02_rman','lpdlvdb02_rman_start','lpgms-sqldb_mssql_lpgms','lpgms-sqldb_mssql_stg','lpenr-sqlclt-t_mssql','lpgcsdb_mssql','LEASEDB','JMDB','JUNJADB','purchqdb','jmtibdb','lpbakdb01_rman','lpbakdb01_rman_start','lpscsdb_mssql')\r\nand started between CAST(CONVERT(VARCHAR(10), GETDATE()-0, 120) AS DATETIME) and CAST(CONVERT(VARCHAR(10), GETDATE()-0, 120) + ' 23:59:59' AS DATETIME)\r\nAND STATUS <= 1\r\ngroup by case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end\r\n-- having min(State)  = 'Done'\r\n"
    },
    {
     "rawSql": "SELECT CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN SVC_NM WHEN 'PolicyName' THEN POL_NM END AS ServiceName\r\n     , POL_NM, ELS_TM, MAX_ELS_TM, SOL_CL_CD\r\n  FROM TB_BAK_SOLPOL_M\r\n --WHERE SVC_NM IN ($ServiceName) --2023.07.21 서버조회조건제거\r\n   -- AND SOL_CL_CD = 'NET'\r\norder by ServiceName"
    }
   ]
  },
  {
   "title": "Backup Batch Time Line(Comvault)  (🟦 : SAN 🟩 : NET)",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "\r\nSELECT Client as POL_NM\r\n     , StartTime\r\n     , EndTime\r\n  FROM TB_CV_BAK_Stat_Chk_L A\r\n WHERE A.CollectDT BETWEEN  CAST(CONVERT(VARCHAR(10), GETDATE()-0, 120) AS DATETIME) and CAST(CONVERT(VARCHAR(10), GETDATE()-0, 120) + ' 23:59:59' AS DATETIME)\r\n   AND A.Agent = 'SQL Server'"
    },
    {
     "rawSql": "SELECT CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN SVC_NM WHEN 'PolicyName' THEN POL_NM END AS ServiceName\r\n     , POL_NM, ELS_TM, MAX_ELS_TM, SOL_CL_CD\r\n  FROM TB_BAK_SOLPOL_M\r\n --WHERE SVC_NM IN ($ServiceName) --2023.07.21 서버조회조건제거\r\n   -- AND SOL_CL_CD = 'NET'\r\norder by ServiceName"
    }
   ]
  },
  {
   "title": "monthly check netbackup (Elapsed Time)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "SELECT CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') time\r\n     , case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end  AS POL_NM\r\n     , max(Elapsed) AS Elapsed \r\n     , min(State) AS State\r\n     , convert(int, avg(KB_Per_Sec)/1024) AS MB_Per_Sec\r\n  FROM TB_Bak_Stat_Chk_L\r\n WHERE CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n   -- AND SCHEDULE = 'full_daily'\r\n   AND STATUS <= 1\r\n--    AND STATUS <> ''\r\n   AND POLICY IN ($PolicyName)\r\ngroup by CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') \r\n     , case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end \r\nhaving min(State)  = 'Done'\r\norder by time desc"
    },
    {
     "rawSql": "SELECT CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN SVC_NM WHEN 'PolicyName' THEN POL_NM END AS ServiceName\r\n     , POL_NM, ELS_TM, MAX_ELS_TM, SOL_CL_CD\r\n  FROM TB_BAK_SOLPOL_M\r\n WHERE SVC_NM IN ($ServiceName)\r\n   AND SOL_CL_CD = 'NET'\r\norder by ServiceName"
    }
   ]
  },
  {
   "title": "monthly check netbackup (Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "rawSql": "SELECT CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') time\r\n     , case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end  AS POL_NM\r\n     , max(Elapsed) AS Elapsed \r\n     , min(State) AS State\r\n     , convert(int, sum(Kilobytes)/1024/max(Elapsed)) AS MB_Per_Sec\r\n  FROM TB_Bak_Stat_Chk_L\r\n WHERE CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n   -- AND SCHEDULE = 'full_daily'\r\n   AND STATUS <= 1\r\n--    AND STATUS <> ''\r\n   AND POLICY IN ($PolicyName)\r\ngroup by CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') \r\n     , case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end \r\nhaving min(State)  = 'Done'\r\norder by time desc"
    },
    {
     "rawSql": "SELECT CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN SVC_NM WHEN 'PolicyName' THEN POL_NM END AS ServiceName\r\n     , POL_NM, ELS_TM, MAX_ELS_TM, SOL_CL_CD\r\n  FROM TB_BAK_SOLPOL_M\r\n WHERE SVC_NM IN ($ServiceName)\r\n   AND SOL_CL_CD = 'NET'\r\norder by ServiceName"
    }
   ]
  },
  {
   "title": "monthly check comvault (Elapsed Time)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "SELECT CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') time\r\n     , CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN T1.ServiceName WHEN 'PolicyName' THEN T1.Policy END AS ServiceName\r\n     -- , T1.Policy\r\n     , T1.Elapsed\r\n     -- , ((T1.ConvertSec * 1.0) / (T1.THRESHOLD * 1.0) * 100) - 100 AS ElapsedPerStd\r\n     , MB_Per_Sec\r\n  FROM (SELECT A.CollectDT\r\n             , B.POL_NM AS Policy\r\n             , B.SVC_NM AS ServiceName\r\n             , CONVERT(INT, DATEDIFF(SECOND, STARTTIME, ENDTIME)) AS Elapsed\r\n             --Elapsed Per Time 계산\r\n             , DATEDIFF(SECOND, STARTTIME, ENDTIME) AS ConvertSec\r\n             , CASE WHEN DATEPART(WEEKDAY, STARTTIME) = 1 THEN B.MAX_ELS_TM\r\n                    ELSE B.ELS_TM \r\n                END AS THRESHOLD\r\n             , Throughput * 3600 / 1024 AS MB_Per_Sec\r\n          FROM TB_CV_BAK_Stat_Chk_L A, TB_BAK_SOLPOL_M B\r\n         WHERE A.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n           AND A.CLIENT = B.POL_NM\r\n           AND B.SVC_NM IN ($ServiceName)\r\n           AND B.SOL_CL_CD = 'CON'\r\n           AND A.Agent = 'SQL Server'\r\n           AND A.Status = 'Completed'\r\n ) T1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "monthly check comvault (Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "rawSql": "SELECT CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') time\r\n     , CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN T1.ServiceName WHEN 'PolicyName' THEN T1.Policy END AS ServiceName\r\n     -- , T1.Policy\r\n     , T1.Elapsed\r\n     -- , ((T1.ConvertSec * 1.0) / (T1.THRESHOLD * 1.0) * 100) - 100 AS ElapsedPerStd\r\n     , MB_Per_Sec\r\n  FROM (SELECT A.CollectDT\r\n             , B.POL_NM AS Policy\r\n             , B.SVC_NM AS ServiceName\r\n             , CONVERT(INT, DATEDIFF(SECOND, STARTTIME, ENDTIME)) AS Elapsed\r\n             --Elapsed Per Time 계산\r\n             , DATEDIFF(SECOND, STARTTIME, ENDTIME) AS ConvertSec\r\n             , CASE WHEN DATEPART(WEEKDAY, STARTTIME) = 1 THEN B.MAX_ELS_TM\r\n                    ELSE B.ELS_TM \r\n                END AS THRESHOLD\r\n             , Throughput * 1024 / 3600 AS MB_Per_Sec\r\n          FROM TB_CV_BAK_Stat_Chk_L A, TB_BAK_SOLPOL_M B\r\n         WHERE A.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n           AND A.CLIENT = B.POL_NM\r\n           AND B.SVC_NM IN ($ServiceName)\r\n           AND B.SOL_CL_CD = 'CON'\r\n           AND A.Agent = 'SQL Server'\r\n           and A.Status = 'Completed'\r\n ) T1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "영업통합 백업량",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT CONVERT(DATETIME, CONVERT(VARCHAR,Started,112) + ' ' + '00' + ':00:00') time\r\n     , Policy\r\n     , SUM(CONVERT(int,Kilobytes*(1-(Dedupe_Ratio/100))/1024))/1024 lpbakdb01_rman -- real_size_gb\r\n  FROM TB_Bak_Stat_Chk_L\r\n WHERE Started between $__timeFrom() and $__timeTo()\r\nAND Policy in ('lpbakdb01_rman')\r\nGROUP BY CONVERT(VARCHAR,Started,112), Policy\r\nORDER BY 1 "
    },
    {
     "rawSql": "SELECT CONVERT(DATETIME, CONVERT(VARCHAR,Started,112) + ' ' + '00' + ':00:00') time\r\n     , Policy\r\n     , SUM(CONVERT(int,Kilobytes*(1-(Dedupe_Ratio/100))/1024))/1024 lpsisdb_arc -- real_size_gb\r\n  FROM TB_Bak_Stat_Chk_L\r\n WHERE Started between $__timeFrom() and $__timeTo()\r\nAND Policy in ('lpsisdb_arc')\r\nGROUP BY CONVERT(VARCHAR,Started,112), Policy\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "monthly check comvault (Elapsed Time, Log)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "SELECT CollectDT time\r\n     , CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN T1.ServiceName WHEN 'PolicyName' THEN T1.Policy END AS ServiceName\r\n     -- , T1.Policy\r\n     , T1.Elapsed\r\n     -- , ((T1.ConvertSec * 1.0) / (T1.THRESHOLD * 1.0) * 100) - 100 AS ElapsedPerStd\r\n     , MB_Per_Sec\r\n  FROM (SELECT a.STARTTIME as CollectDT\r\n             , B.POL_NM AS Policy\r\n             , B.SVC_NM AS ServiceName\r\n             , CONVERT(INT, DATEDIFF(SECOND, STARTTIME, ENDTIME)) AS Elapsed\r\n             --Elapsed Per Time 계산\r\n             , DATEDIFF(SECOND, STARTTIME, ENDTIME) AS ConvertSec\r\n             , CASE WHEN DATEPART(WEEKDAY, STARTTIME) = 1 THEN B.MAX_ELS_TM\r\n                    ELSE B.ELS_TM \r\n                END AS THRESHOLD\r\n             , Throughput * 3600 / 1024 AS MB_Per_Sec\r\n          FROM TB_CV_BAK_Stat_Chk_L A, TB_BAK_SOLPOL_M B\r\n         WHERE A.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n           AND A.CLIENT = B.POL_NM\r\n           AND B.SVC_NM IN ($ServiceName)\r\n           AND B.SOL_CL_CD = 'CON'\r\n           AND A.Agent != 'SQL Server'\r\n           And A.Status = 'Completed'\r\n ) T1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "monthly check comvault (Throughput, Log)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "rawSql": "SELECT CollectDT time\r\n     , CASE ${DisplayType:singlequote} WHEN 'ServiceName' THEN T1.ServiceName WHEN 'PolicyName' THEN T1.Policy END AS ServiceName\r\n     -- , T1.Policy\r\n     , T1.Elapsed\r\n     -- , ((T1.ConvertSec * 1.0) / (T1.THRESHOLD * 1.0) * 100) - 100 AS ElapsedPerStd\r\n     , MB_Per_Sec\r\n  FROM (SELECT a.STARTTIME as CollectDT\r\n             , B.POL_NM AS Policy\r\n             , B.SVC_NM AS ServiceName\r\n             , CONVERT(INT, DATEDIFF(SECOND, STARTTIME, ENDTIME)) AS Elapsed\r\n             --Elapsed Per Time 계산\r\n             , DATEDIFF(SECOND, STARTTIME, ENDTIME) AS ConvertSec\r\n             , CASE WHEN DATEPART(WEEKDAY, STARTTIME) = 1 THEN B.MAX_ELS_TM\r\n                    ELSE B.ELS_TM \r\n                END AS THRESHOLD\r\n             , Throughput * 1024 / 3600 AS MB_Per_Sec\r\n          FROM TB_CV_BAK_Stat_Chk_L A, TB_BAK_SOLPOL_M B\r\n         WHERE A.CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n           AND A.CLIENT = B.POL_NM\r\n           AND B.SVC_NM IN ($ServiceName)\r\n           AND B.SOL_CL_CD = 'CON'\r\n           AND A.Agent != 'SQL Server'\r\n           And A.Status = 'Completed'\r\n ) T1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "넷백업 전체 조회",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "rawSql": "SELECT CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') time\r\n     , case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end  AS POL_NM\r\n   --   , substring(convert(varchar, Started, 108),1,4) + '0 ' + case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end  AS POL_NM\r\n   --   , convert(convert(varchar, Started, 108))\r\n     , max(Elapsed) AS Elapsed \r\n   --   , min(State) AS State\r\n   --   , convert(int, avg(KB_Per_Sec)/1024) AS MB_Per_Sec\r\n  FROM TB_Bak_Stat_Chk_L\r\n WHERE CollectDT BETWEEN  REPLACE(SUBSTRING($__timeFrom(),1,10),'-','') AND  REPLACE(SUBSTRING(CONVERT(VARCHAR,DATEADD(MONTH,1,CONVERT(DATETIME, $__timeTo()))-1, 112),1,10),'-','')\r\n   -- AND SCHEDULE = 'full_daily'\r\n   AND STATUS <= 1\r\n--    AND STATUS <> ''\r\n   -- AND POLICY IN ($PolicyName)\r\n   -- and Policy not like '%fs'\r\n   and policy in ('lpbakdb01_rman',\r\n'lpsisdb_arc',\r\n'lpdwsdb01_netezza',\r\n'lpmosdb_arc',\r\n'lpscsdb01_tr_fs',\r\n'lpgcsdb01_tr_fs',\r\n'lpenr-sqlclt-t_tr_fs',\r\n'lpea-sqldb_tr_fs',\r\n'lpgms-sqldb_tr_fs',\r\n'lpscsdb01_mssql',\r\n'lpgms-sqldb_mssql_lpgms',\r\n'lpea-sqldb_mssql',\r\n'lpbakdb02_rman',\r\n'ld-hrdb01_rman',\r\n'lpgcsdb_mssql',\r\n'lpenr-sqlclt-t_mssql',\r\n'lpgms-sqldb_mssql_stg'\r\n)\r\n   -- and Policy not like '%test%'\r\n   and policy is not null\r\n   and policy <> ''\r\ngroup by CONVERT(DATETIME, CollectDT + ' ' + '00' + ':00:00') \r\n     , case when Policy like '%rman_start' then replace(Policy,'_start','') else Policy end\r\nhaving min(State)  = 'Done'\r\norder by time desc"
    }
   ]
  }
 ]
}