{
 "title": "SQL Server Alert",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "PartName",
    "query": "SELECT 'MD' AS PartName\nUNION\nSELECT '마케팅' AS PartName\nUNION\nSELECT '경영지원' AS PartName\nUNION\nSELECT '재무' AS PartName\nUNION\nSELECT 'POS' AS PartName\nUNION\nSELECT '상품권' AS PartName\nUNION\nSELECT '인프라' AS PartName"
   },
   {
    "name": "ServerName",
    "query": "usp_get_DBA_Target_Svr 'row', \"$PartName\""
   }
  ]
 },
 "panels": [
  {
   "title": "Alert List",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "dataset": "MonitoringDB" }
   ]
  },
  {
   "title": "락 카운트 (전체)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "SELECT ISNULL(w.CollectDate, GETDATE()) as time, substring(i.ServerName, 2, charindex(']', i.ServerName)-2) as PartName, i.ServerName, SUM(case when w.Blocking_session_id > 0 then 1 else 0 end) CNT \r\nFROM META2_M_InstanceInfo i (nolock)\r\nLEFT OUTER JOIN TBL2_M_WhoIsActive w (nolock)\r\nON w.instanceID = i.instanceID \r\nAND w.CollectDate BETWEEN $__timeFrom() AND $__timeTo()\r\n-- AND w.Blocking_session_id > 0\r\nWHERE 1=1\r\nAND i.ServerName not like '%점%'\r\nand i.ServerName not like '%몰%'\r\nand i.ServerName not like '%아울렛%'\r\nand i.UseYN = 'Y'\r\nGROUP BY w.CollectDate, substring(i.ServerName, 2, charindex(']', i.ServerName)-2), i.ServerName\r\norder by time"
    }
   ]
  },
  {
   "title": "세션 카운트 (전체)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "SELECT w.CollectDate as time, substring(i.ServerName, 2, charindex(']', i.ServerName)-2) as PartName, i.ServerName, COUNT(1) CNT \r\nFROM TBL2_M_WhoIsActive w (nolock), META2_M_InstanceInfo i (nolock)\r\nWHERE w.instanceID = i.instanceID \r\nAND w.CollectDate BETWEEN $__timeFrom() AND $__timeTo()\r\nAND i.ServerName not like '%점%'\r\n-- AND i.instanceID <> 51\r\nand i.ServerName not like '%점%'\r\nand i.ServerName not like '%몰%'\r\nand i.ServerName not like '%아울렛%'\r\nand i.UseYN = 'Y'\r\nGROUP BY w.CollectDate, substring(i.ServerName, 2, charindex(']', i.ServerName)-2), i.ServerName\r\norder by time"
    }
   ]
  },
  {
   "title": "Annotations list",
   "type": "annolist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "dataset": "MonitoringDB" }
   ]
  },
  {
   "title": "MS-SQL Instance 정보",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "select -- charindex('[', ServerName) st_col, charindex(']', ServerName) end_col, \r\nsubstring(ServerName, 2, charindex(']', ServerName)-2) as PartName, ServerName, InstanceID\r\nfrom MonitoringDB.dbo.META2_M_InstanceInfo i\r\nwhere 1=1\r\nand ServerName not like '%점%'\r\nand ServerName not like '%몰%'\r\nand ServerName not like '%아울렛%'\r\nand UseYN = 'Y'\r\norder by PartName, ServerName"
    }
   ]
  },
  {
   "title": "리소스 체크",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "MonitoringDB",
     "rawSql": "\r\nselect * FROM MonitoringDB.dbo.TB_Svr_Rsrc_Chk_L \r\nwhere 1=1\r\n-- and  CollectDT = '20231109'\r\nand hostname = 'lddlvdb01'\r\norder by CollectDT, collecthh"
    }
   ]
  }
 ]
}